### ISSUE TITLE
Add language property to index.yaml

### ISSUE THREAD

**Issue by makandre** [appsody/stacks#100]
**Is your feature request related to a problem? Please describe.**

I'm working on the appsody extension for Codewind, specifically for this issue https://github.com/kabanero-io/appsodyExtension/issues/23.  We want the extension code to consume the appsody index directly, eliminating the need to have an intermediate Codewind template index (i.e.  https://github.com/kabanero-io/codewind-appsody-templates).  One property that Codewind requires is a `language` property

**Describe the solution you'd like**

Would it be possible to add a `language` property to index.yaml?  Values would be `java`, `nodejs`, `swift`, `python`, etc.

**Describe alternatives you've considered**

If not, then I can resort to inferring the language from the `keywords`

**Additional context**

**Comment by neeraj-laad** [comment]
@makandre Thanks for raising this issue. There is some work in progress on the stack.yaml and index.yaml. I will try to address this with those.

**Comment by neeraj-laad** [comment]
@makandre Can you please explain what does CodeWind do with the language information? Appsody does not do anything special based on the language used in the stack so would like to understand this first, before we add this in.

**Comment by makandre** [comment]
Codewind uses the language for 1) display purposes 2) determine the style of debugging (e.g. node vs java)

But in the larger context of Codewind extensions, we may want to allow an extension to use the language value to dictate some aspect of the way it behaves.

**Comment by makandre** [comment]
I'm closing this in favour of #131
