### ISSUE TITLE
1 high severity vulnerability

### ISSUE THREAD

**Issue by mhmxs** [appsody/stacks#108]
**Describe the bug**
I found the following during test execution:
```
[Container] Running Install: npm install --prefix user-app
2019/07/24 08:21:28 Health check error. Ignore and retry: Get http://localhost:3000/health: EOF
2019/07/24 08:21:30 Health check error. Ignore and retry: Get http://localhost:3000/health: EOF
added 170 packages from 578 contributors and audited 295 packages in 3.331s
[Container] found 1 high severity vulnerability
[Container]   run `npm audit fix` to fix them, or `npm audit` for details
[Container] Running: npm start
[Container]
[Container] > nodejs-express@0.2.1 start /project
[Container] > node server.js
```

**To Reproduce**
1. execute `make test`

**Comment by tomleah** [comment]
Looks like this vulnerability is further down the dependency tree.

Proposing we add `npm audit fix` when we `npm install` as a safety net as well as finding the stage where this vulnerability is introduced.

**Comment by tomleah** [comment]
Security vulnerability is in `lodash` < 4.17.12 (see: https://www.npmjs.com/advisories/1065) yargs-unparser is using an old version of lodash, a pull request to fix this is open here
https://github.com/yargs/yargs-unparser/pull/39

**Comment by tomleah** [comment]
https://github.com/appsody/stacks/pull/112 should help out until the fix is merged into `yargs-unparser` 🙂
