### ISSUE TITLE
Support multiple repositories

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#118]
Today we only have one template for each stack. 

We need to be able to support multiple templates and users should able to select which one they need.

**Comment by kylegc** [comment]
So my thinking on this is we should use a long identifier format similar to this: `repo/stack:version/template`

The `appsody list` command should output all of these details (format options below).

The `appsody init` command should accept short identifiers (a.k.a. just the stack name) _if_ there are no conflicts. When conflicts occur, more detail is needed. For example, if there is a "nodejs" stack in two different repos, the user would have to specify the repo on the init command, e.g. `appsody init incubator/nodejs`. Likewise, if there are to versions of "nodejs", you'd have to resolve the conflict by specifying the version, e.g. `appsody init nodejs:0.2.2`. (Maybe we could calculate the latest version and use as default?)

An exception to this conflict resolution is the templates where we specify a default in the index.yaml. So if no template is specified on init, the default is used.

Some options for `appsody list` output:

```
REPOSITORY       STACK             	VERSION    TEMPLATE     	DESCRIPTION                              
incubator        nodejs           	0.2.2      simple       	Node.js Runtime                          
incubator        nodejs-express   	0.2.2      simple       	Express web framework for Node.js        
incubator        nodejs-express   	0.2.2      skaffold       	Express web framework for Node.js        
incubator        swift            	0.1.0      simple       	Swift runtime                            
incubator        java-microprofile	0.2.2      default      	Microprofile using AdoptOpenJDK and Maven
incubator        java-spring-boot2	0.3.2      default      	Spring Boot using IBM Java SDK and Maven 
incubator        java-spring-boot2	0.3.2      kotlin       	Spring Boot using IBM Java SDK and Maven 
```

```
STACK                                         	DESCRIPTION                              
incubator/nodejs:0.2.2/simple                   Node.js Runtime                          
incubator/nodejs-express:0.2.2/simple       	Express web framework for Node.js        
incubator/nodejs-express:0.2.2/skaffold       	Express web framework for Node.js        
incubator/swift:0.1.0/simple                    Swift runtime                            
incubator/java-microprofile:0.2.2/default      	Microprofile using AdoptOpenJDK and Maven
incubator/java-spring-boot2:0.3.2/default      	Spring Boot using IBM Java SDK and Maven 
incubator/java-spring-boot2:0.3.2/kotlin       	Spring Boot using IBM Java SDK and Maven 
```

**Comment by tomleah** [comment]
Here are some thoughts
## Phase 1: Multiple repos
**Note:** I **do not consider** multiple templates at this stage.
1) We have the default repo as our `stable-index.yaml`.
Doing `appsody init nodejs` would use the latest `nodejs` stack from the stable repository.
2) Additional repos are added and the init command would change to `appsody init <repo-name>/nodejs`.
3) `appsody list` would show like Kyles first proposal
```
REPOSITORY    STACK             VERSION     DESCRIPTION    
stable        nodejs            0.2.2       Node.js Runtime
incubator     nodejs-express    0.2.2       Express web framework for Node.js
```
## Phase 2: Multiple starters
**Note:** this phase is aware of phase 1.
1) `appsody init nodejs-express` - will use the default starter (identified in `stack.yaml`) 
2) `appsody init nodejs-express skaffold` - will use the `skaffold` starter
3) `appsody list` 
```
REPOSITORY    STACK             VERSION     DESCRIPTION                           DEFAULT STARTER
stable        nodejs            0.2.2       Node.js Runtime                       simple
incubator     nodejs-express    0.2.2       Express web framework for Node.js     simple
```
4) `appsody list <stack-name>` - `appsody list nodejs-express`
```
NAME        VERSION      DESCRIPTION (🤔)
simple      0.1.0        We should maybe have descriptions for starters?
skaffold    0.2.0        We should maybe have descriptions for starters?
```

## Phase 3: Versioning of stacks
...

**Comment by tomleah** [comment]
## Meeting Notes - 31/07/2019 
`appsody list`
- Add REPOSITORY column
``` 
REPOSITORY    STACK             VERSION     DESCRIPTION
stable        nodejs            0.2.2       Node.js Runtime
incubator     nodejs-express    0.2.2       Express web framework for Node.js
 ```
`~/.appsody/.appsody.yaml`
- Add config file that will set the default repository. This will be the stable index by default.
