### ISSUE TITLE
Errors when importing Node.js Express project into Eclipse

### ISSUE THREAD

**Issue by eharris369** [appsody/stacks#126]
**Describe the bug**
There are errors for the launch.json and tasks.json files when importing a Node.js Express project into Eclipse.  It does not like the comments in both files and the trailing ',' in tasks.json:

- Expected name at 2:4	launch.json	/appsodyNode1/.vscode	line 2	JSON Problem
- Expected name at 2:4	tasks.json	/appsodyNode1/.vscode	line 2	JSON Problem
- Expected value at 48:4	tasks.json	/appsodyNode1/.vscode	line 48	JSON Problem

**To Reproduce**
1. Create an appsody Node.js Express project
2. Using Eclipse IDE for Enterprise Java Developers (https://www.eclipse.org/downloads/packages/release/2019-06/r/eclipse-ide-enterprise-java-developers), import the project into Eclipse using the **File** > **Import** > **General** > **Projects from Folder or Archive** wizard

**Actual behaviour**
Errors in the Markers view for the imported project

**Environment Details (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: latest

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by neeraj-laad** [comment]
Thanks @eharris369 for raising this issue.
We will investigate and update the status here shortly.
