### ISSUE TITLE
Provide "post" hooks as part of index.yaml generation

### ISSUE THREAD

**Issue by ianpartridge** [appsody/stacks#129]
Because we intend this build tooling to be reused by downstream users, provide hooks to support generation of custom YAML.

1. After generating each template.
2. After generating each stack.

**Comment by ianpartridge** [comment]
@neeraj-laad

**Comment by neeraj-laad** [comment]
Post hooks can be added to the build.sh file, without needing any special change on the existing build system. 

Closing this for now. Please re-open if I have misunderstood this requirement.
