### ISSUE TITLE
java-microprofile Dockerfile WORKDIR setting causes appsody init Error

### ISSUE THREAD

**Issue by dacleyra** [appsody/stacks#14]
```
Running appsody init...
Downloading java-microprofile template project from https://github.com/appsody/stacks/releases/download/0.2.0/incubator.java-microprofile.templates.default.tar.gz
Download complete. Extracting files from java-microprofile.tar.gz
Successfully initialized java-microprofile project
Setting up the development environment
Running command: docker[pull appsody/java-microprofile:0.2]
Running command: docker[run --rm --entrypoint /bin/bash appsody/java-microprofile:0.2 -c find / -type f -name .appsody-init.sh]
[Error] Could not run the docker image: exit status 1
[Error] Failed to run the find command for the .appsody-init.sh on the stack image: appsody/java-microprofile:0.2
```

This fails because WORKDIR is set
https://github.com/appsody/stacks/blob/master/incubator/java-microprofile/image/Dockerfile-stack#L16

Detached `docker run` commands will run in the WORKDIR, so `.appsody-init.sh` will never be found.

Either WORKDIR needs to be changed in the Dockerfile, or the `docker run` needs to specify `--workdir`

**Comment by neeraj-laad** [comment]
@dacleyra Please can you confirm the version of appsody cli you are using? `appsody version`

**Comment by dacleyra** [comment]
`appsody 0.2.1`

**Comment by kylegc** [comment]
Please update to `appsody 0.2.2`, this issue has been fixed.

If you installed on macOS with brew, simply run:
`brew upgrade appsody`
