### ISSUE TITLE
Build system re-builds all stacks when only one stack has been modified

### ISSUE THREAD

**Issue by tomleah** [appsody/stacks#141]
**Describe the bug**
See https://travis-ci.com/appsody/stacks/builds/122069698
When only `.appsody-config` is changed in the microprofile stack all the stacks were rebuilt by travis and not only the microprofile stack.

We should change this to reduce the build times.

**To Reproduce**
Look on https://travis-ci.com/appsody/stacks/builds/122069698

**Expected behavior**
Only build stacks that have been modified in a pull request

**Actual behaviour**
Builds all stacks

**Comment by tomleah** [comment]
cc: @mhamwala

**Comment by mhamwala** [comment]
**exhibit 1:** changed a README at stack level, build skips as expected
https://travis-ci.com/appsody/stacks/builds/122079223
