### ISSUE TITLE
Appsody build uses hardcoded directory name in list.sh

### ISSUE THREAD

**Issue by groeges** [appsody/stacks#153]
**Describe the bug**
If forking the apposdy git repo into another repo, which doesn't have the name `stacks` as its name, when the list.sh script is executed as part of running build.sh, no stacks are detected. 

**To Reproduce**
1. Easiest way to recreate, rather than forka new repo etc, is to rename the `stacks` directory of an already cloned `appsody/stacks` repo, which will simulate having a different repo name.
2. cd to the `./ci` directory
3. run `./build.sh ../`
4. See that no stacks are built !!

**Expected behavior**
The full set of stacks in the incubator, stable and experimental directories should be found.
ie: from my working system (slightly back level)
```
Generated list for all stacks
STACKS_LIST=incubator/nodejs-express incubator/nodejs incubator/swift
SKIPPING: /Users/stevengroeger/appsody/stacks/experimental
```
**Actual behaviour**
There are no stacks detected and the list of stacks is shown as  
```
Listing all stacks
STACKS_LIST=/Users /Users /Users /Users /Users /Users /Users
```

**Additional context**
The failing line in list.sh is: https://github.com/appsody/stacks/blob/a0b6787c2a46b5b901f94f88a04ba99e2ec78f89/ci/list.sh#L47
```
 var=`echo $stack_exists | sed 's/.*stacks\///'`
```
which uses `stacks` as the directory it is searching in, whereas it should use the basename of the $base_dir variable.

**Comment by mhamwala** [comment]
Thanks for spotting this @groeges, putting a fix in shortly.
