### ISSUE TITLE
Missing docker image  for quarkus stack 

### ISSUE THREAD

**Issue by spoole167** [appsody/stacks#175]
The quarkus config does not work as docker image  appsody/java-quarkus:0.1 does not exist. It should be appsody/quarkus if what is on docker hub is to be beleived 
 
appsody init experimental/quarkus

Running appsody init...
Downloading quarkus template project from https://github.com/appsody/stacks/releases/download/quarkus-v0.1.0/experimental.quarkus.templates.default.tar.gz
Download complete. Extracting files from quarkus.tar.gz
Setting up the development environment
Running command: docker[pull appsody/java-quarkus:0.1]
[Warning] Docker image pull failed: exit status 1
[Warning] The stack init script failed: Failed to run the docker find command: Could not find the image either in docker hub or locally: appsody/java-quarkus:0.1
[Warning] Your local IDE may not build properly, but the Appsody container should still work.
[Warning] To try again, resolve the issue then run `appsody init` with no arguments.

**Comment by mhamwala** [comment]
Thanks for spotting this @spoole167, we will rectify the issue asap, you are right the `.appsody-config.yaml` should be pointing at `stack: appsody/quarkus:0.1`
