### ISSUE TITLE
Generate .appsody-config.yaml when creating the project

### ISSUE THREAD

**Issue by kewegner** [appsody/stacks#215]
Per @ebullient 

.appsody-config.yaml is currently checked into the starters inside the stack. This creates technical debt for the stack, as the .appsody-config.yaml in each starter in the stack has to also be updated when the version changes.

The .appsody-config.yaml file should be generated at project create time to use the version of the stack that created it.

**Comment by neeraj-laad** [comment]
There are a few cases we might want to consider: 

- For <repo>-index-local.yamls, we should use the full version string like nodes-express `0.2.3`. This will make it easy for users to test their stack changes locally.

- For <repo>-index.yamls, we might want to check the major version and decide how to best deal with this
   - if major < 0, use major.minor as the version `0.2`
   - if major > 1, use just het major version `0`
