### ISSUE TITLE
Quarkus stack test fail on second execution

### ISSUE THREAD

**Issue by edewit** [appsody/stacks#216]
**Describe the bug**
Running `appsody test` a second time on a quarkus stack will result in failed tests

**To Reproduce**
1. `appsody init experimental/quarkus`
1. `appsody test`
1. `appsody test`
1. See error:
```
[Container] 2019-08-21 13:11:50,977 INFO  [io.quarkus] (main) Installed features: []
[Container] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.166 s <<< FAILURE! - in org.acme.quickstart.GreetingResourceTest
[Container] [ERROR] testHelloEndpoint  Time elapsed: 0.597 s  <<< ERROR!
[Container] java.net.ConnectException: Connection refused (Connection refused)
[Container] 	at org.acme.quickstart.GreetingResourceTest.testHelloEndpoint(GreetingResourceTest.java:17)
[Container] 
[Container] [ERROR] testGreetingEndpoint  Time elapsed: 0.017 s  <<< ERROR!
[Container] java.net.ConnectException: Connection refused (Connection refused)
[Container] 	at org.acme.quickstart.GreetingResourceTest.testGreetingEndpoint(GreetingResourceTest.java:28)
[Container] 
[Container] 2019-08-21 13:11:51,604 INFO  [io.quarkus] (main) Quarkus stopped in 0.000s
[Container] [INFO] 
[Container] [INFO] Results:
[Container] [INFO] 
[Container] [ERROR] Errors: 
[Container] [ERROR]   GreetingResourceTest.testGreetingEndpoint:28 ? Connect Connection refused (Con...
[Container] [ERROR]   GreetingResourceTest.testHelloEndpoint:17 ? Connect Connection refused (Connec...
[Container] [INFO] 
[Container] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
```

**Expected behavior**
Test don't fail

**Environment Details (please complete the following information):**
 - OS: Fedora release 30 (Thirty)
 - Browser Chrome 76.0.3809.100 (Official Build) (64-bit)

**If applicable please specify:**
 - CLI version: appsody 0.3.0
 - Stack you are using: quarkus

**Comment by mhamwala** [comment]
Thanks for raising this @edewit!

This issue might be linked to: https://github.com/appsody/stacks/tree/master/experimental/quarkus#known-issues

cc: @paulrobinson

**Comment by edewit** [comment]
@mhamwala right

**Comment by paulrobinson** [comment]
Thanks @edewit for fixing it :-)

Yes @mhamwala, this is one of the listed known issues.

**Comment by paulrobinson** [comment]
@edewit be sure to remove the known issue from the readme in your PR :-)

**Comment by edewit** [comment]
good point @paulrobinson updated the PR
