### ISSUE TITLE
kabanero pipeline to build spring-boot2 stack failing with Non-resolvable parent POM for dev.appsody:application:0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by kvijai82** [appsody/stacks#224]
When trying to build the java-spring-boot2 stack using a Tekton pipeline I am getting the following failure about non resolvable parent POM.  Is there a version mismatch somewhere? 

Steps to reproduce:
- Did an appsody init java-spring-boot2
- Was able to do an appsody build locally successfully
- Pushed it to a git repo (https://github.com/kvijai82/appsody-java-spring-boot2)
- Ran pipeline in an OKD cluster to build the repo above and failed with the error.

``
INFO[0030] args: [-c /project/java-spring-boot2-build.sh package] 
Installing parent dev.appsody:spring-boot2-stack:0.3.4
> mvn install -q -f /project/appsody-boot2-pom.xml
Updating parent version
> mvn -q versions:update-parent -DparentVersion=[0,1)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for dev.appsody:application:0.0.1-SNAPSHOT: Could not find artifact dev.appsody:spring-boot2-stack:pom:0.3.3 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at no local POM @ line 6, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project dev.appsody:application:0.0.1-SNAPSHOT (/project/user-app/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for dev.appsody:application:0.0.1-SNAPSHOT: Could not find artifact dev.appsody:spring-boot2-stack:pom:0.3.3 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at no local POM @ line 6, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Package project in the foreground
> mvn clean package verify
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for dev.appsody:application:0.0.1-SNAPSHOT: Failure to find dev.appsody:spring-boot2-stack:pom:0.3.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project dev.appsody:application:0.0.1-SNAPSHOT (/project/user-app/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for dev.appsody:application:0.0.1-SNAPSHOT: Failure to find dev.appsody:spring-boot2-stack:pom:0.3.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
error building image: error building stage: waiting for process to exit: exit status 1
[root@kalathur-okd-dal-master common]# 
``

**Comment by ebullient** [comment]
`Non-resolvable parent POM for dev.appsody:application:0.0.1-SNAPSHOT: Could not find artifact dev.appsody:spring-boot2-stack:pom:0.3.3 in central `

There is a mismatch/problem: the pom.xml in the initialized project is asking for a non-present version of the parent pom.

**Comment by kvijai82** [comment]
Updated the version in the pom.xml from 0.3.3 to 0.3.4 to avoid the version mismatch and that resolved the problem.  Thanks @ebullient!
