### ISSUE TITLE
Errors when importing Java Microprofile (0.2.8) project into Eclipse 

### ISSUE THREAD

**Issue by keithchong** [appsody/stacks#230]
**Describe the bug**
This is a very similar issue to https://github.com/appsody/stacks/issues/126

In 0.2.8, the .vscode config files were added https://github.com/appsody/stacks/pull/228

After importing these projects into Eclipse, the JSON validator flags those comments as errors since they are not allowed in JSON

Another possible issue is that IDE specific metadata should not be included in project templates because the projects can be imported into any IDE.

**To Reproduce**
See the reference Issue for steps but use 0.2.8 MP project

**Expected behavior**
No errors are expected

**Actual behaviour**
See the reference Issue for similar errors reported

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] Mac OS

**If applicable please specify:**
 - CLI version: 0.3.0
 - Stack you are using: Java MicroProfile 0.2.8

**Screenshots**
![Screen Shot 2019-08-22 at 12 08 04 PM](https://user-images.githubusercontent.com/7726022/63532888-b3807b80-c4d9-11e9-9713-7220ed5119b0.png)

**Additional context**
None

**Comment by tomleah** [comment]
https://github.com/appsody/stacks/issues/230 should fix this, however the change will not be effective until the next version of `java-microprofile` is released

**Comment by tomleah** [comment]
`java-microprofile-v0.2.10` has now been released which contains the fix 🙂
