### ISSUE TITLE
Loopback stack does not pick up changes

### ISSUE THREAD

**Issue by makandre** [appsody/stacks#232]
**Describe the bug**

I use `appsody run` on nodejs-loopback project.  When I make a change to one of the source `.ts` file, I see appsody will rerun the `npm start` command.

However, the changes are not reflected in the application.  Since this is typescript, doesn't it need to do an `npm run build` to update the files in `dist`?

**To Reproduce**

**Expected behavior**

After changing a source file, the change is seen in the application

**Actual behaviour**
What is the actual behaviour.

The change is not seen unless I kill `appsody run` and rerun it

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] Mac OS

**If applicable please specify:**
 - CLI version: 0.3.0
 - Stack you are using: nodejs-loopback:0.1

**Screenshots**

**Additional context**

**Comment by neeraj-laad** [comment]
@raymondfeng

**Comment by raymondfeng** [comment]
We watch for `*.ts` files using `ENV APPSODY_WATCH_REGEX="^.*.ts$"`. See https://github.com/appsody/stacks/blob/master/incubator/nodejs-loopback/image/Dockerfile-stack#L8. Does appsody match `*.ts` files recursively?

**Comment by raymondfeng** [comment]
Can you try #256?

**Comment by makandre** [comment]
Thank you, tried the new release, problem is fixed.
