### ISSUE TITLE
Update app-deploy files to use new API

### ISSUE THREAD

**Issue by arthurdm** [appsody/stacks#233]
We have updated (before our initial release) the APIs of the Appsody Operator to be `v1beta1`, as per https://github.com/appsody/appsody-operator/pull/72

Therefore the `app-deploy.yaml` files need to be updated, and the operator redeployed into current dev/test clusters to pickup the new version.

**Comment by arthurdm** [comment]
fyi @seabaylea @neeraj-laad

**Comment by Kamran64** [comment]
They've all been updated and the stacks have been released as of this morning :)
