### ISSUE TITLE
Timing of compile changes when using appsody run and spring boot stack

### ISSUE THREAD

**Issue by GregDritschler** [appsody/stacks#252]
**Describe the bug**
When I modify an application that is using the java-spring-boot2 stack, appsody detects the change, rebuilds the application and restarts the container.  The rebuild and restart appear to overlap (see attached log).  Sometimes the application works afterward and sometimes it does not.

**Expected behavior**
Application runs with the code changes that were made.

**Actual behaviour**
Sometimes the application won't work.  Instead I get 404 indicating the path isn't found.  Canceling the current 'appsody run' session and starting a new 'appsody run' session makes it work again.

Coincidentally when this happens, one of the actuator endpoints drops out as well.  The log says "Exposing 3 endpoint(s) beneath base path '/actuator'".  Normally there are 4 endpoints beneath /actuator.  One of the 4 actuator endpoints 404s. 

**Environment Details (please complete the following information):**
 - OS: Windows 10

**If applicable please specify:**
 - CLI version: 0.3.0
 - Stack you are using: java-spring-boot2

**Screenshots**
[appsody-run-error.txt](https://github.com/appsody/stacks/files/3536090/appsody-run-error.txt)

**Comment by neeraj-laad** [comment]
@ebullient @BarDweller

**Comment by BarDweller** [comment]
Which part of the app were you modifying ?

**Comment by GregDritschler** [comment]
I am modifying Java files using a text editor.

**Comment by BarDweller** [comment]
Specifically which Java files ?

**Comment by ebullient** [comment]
Ozzy is asking which file is being actively modified for a reason: Changes to the “main” class are atypical, and don’t always lead to good results. The most recent Spring stack moves the liveness endpoint out of the Main class, to reduce the temptation to do that.  Outside of the main class, things should behave better..
