### ISSUE TITLE
Stack name in appsody config file is different than what is expected by appsody operator

### ISSUE THREAD

**Issue by mtamboli** [appsody/stacks#283]
**Describe the bug**
When you initialize a project using appsody stack, .appsody-config.yaml file with `stack` is created.
Foe example:
`stack: appsody/java-spring-boot2:0.3`

But app-deploy.yaml is needed for appsody operator. Since it is not auto generated, user will look for the stack name in the generated file and put it in deploy file. But the appsody operator does not like that stack name. It needs to be changed to `java-spring-boot2`. So we need to make sure that they match.

Here is the list of default stack names expected by the appsody operator.
https://github.com/appsody/appsody-operator/blob/master/deploy/stack_defaults.yaml

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by skoh7645** [comment]
@mtamboli Could this be something we add to docs to guide users instead? The `appsody-config.yaml` file is used heavily by the CLI and refers to the actual docker image name rather than just being the stack name

**Comment by ebullient** [comment]
Right. I think the operator is what needs to change here. `.appsody-config.yaml`  has always contained the image name (and that will increasingly be a qualified name.. )

**Comment by mtamboli** [comment]
Thanks for your comments. I will talk to @arthurdm for his thoughts to avoid this. Having a pre-generated app-deploy.yaml file will definitely help here as the stack will be pre-populated. Not sure if appsody operator should be able to work with more qualified name than it expects :-)

**Comment by ebullient** [comment]
Arthur and I had a conversation about this awhile ago -- those defaults should move to the stack (and may have already). The only defaults the operator should have is to cover a default/catch-all case.

**Comment by arthurdm** [comment]
When generating via `appsody deploy --generate-only` the file `app-deploy.yaml` already comes with the correct stack name.

**Comment by ebullient** [comment]
https://github.com/appsody/stacks/issues/194 is the conversation I was thinking about

**Comment by mtamboli** [comment]
I have been using `appsody deploy --generate-only ` and it seems to be working good without the need of changing anything. 

But I am not sure how would a developer will figure this out this option though. I did not know about this until @arthurdm told me about it.

I can close this issue as with the above command, user does not to look into appsody-config for stack name.

**Comment by arthurdm** [comment]
that's a valid point @mtamboli - I believe the pipeline code now has an error msg saying to run `appsody deploy --generate-only` if it doesn't find `app-deploy.yaml`, so that will be how users get to know about it.

**Comment by mtamboli** [comment]
Closing this issues as there is nothing more to fix here. Thanks!
