### ISSUE TITLE
java-spring-boot2: "appsody run" does not reflect changes

### ISSUE THREAD

**Issue by skoh7645** [appsody/stacks#294]
**Describe the bug**
`appsody run` does not reflect changes of application code automatically on refresh. I am having to stop `appsody run` and run it again to see the changes.

**To Reproduce**
1.  Run `appsody run`
2. Go to http://localhost:8080/
3. Change application code
4. Refresh webpage
5. Changes are not reflected on webpage

**Expected behavior**
`appsody run` will show code changes on refresh

**Actual behaviour**
`appsody run` needs to be rerun to view code changes on refresh

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version: 0.4.1
 - Stack you are using: java-spring-boot2

**Screenshots**

**Additional context**

**Comment by skoh7645** [comment]
@ebullient I would like to get your thoughts on how common this use case is. Currently the watcher picks up changes in the "main/java" folder but not the "main/resources" folder.

**Comment by skoh7645** [comment]
Thank you @BarDweller for investigating this. I have submitted a website PR to update our docs on the default value for `APPSODY_WATCH_REGEX` https://github.com/appsody/website/pull/220

**Comment by BarDweller** [comment]
I'll follow up to this with a change for the Spring Boot stacks to swap the regex to `.*`. Anything else will create situations where updates won't occur when expected. This comes at the cost of the stack rebuilding more often than likely needed, (especially when an IDE [ie vscode] is in use that is handling maven recompiles to the target dir. May yet need to revisit a way to allow an IDE to indicate the watching behavior is not required.

**Comment by ebullient** [comment]
Related to #252
