### ISSUE TITLE
Java-Microprofile: No starter app on the default route!

### ISSUE THREAD

**Issue by lroseblade** [appsody/stacks#30]
Once the stack is installed and the user goes to https://locahost:9080 they receive a 404 error as there is no starter app defined and assigned to the end point.

**Comment by neeraj-laad** [comment]
@Emily-Jiang Would like to know your thoughts on this issue.

**Comment by barecode** [comment]
Proposing a change in a PR shortly...

**Comment by barecode** [comment]
Proposed a small PR to make the default context root behave a little more user friendly. This does change the binding in the app away from /starter to /, but I think its an improvement in the initial user experience... especially when they are validating that they have appsody working properly.

**Comment by neeraj-laad** [comment]
This has been resolved in version 0.2.2. We now have a single index.html that users can remove if needed.
