### ISSUE TITLE
java microprofile build image is corrupted when using kaniko

### ISSUE THREAD

**Issue by kvijai82** [appsody/stacks#303]
**Describe the bug**
When we tried to build the java-microprofile stack using a pipeline which is using Kaniko, the image was not running with correct server.xml.  We suspect this is due to a bug in Kaniko running this step in the Dockerfile (https://github.com/appsody/stacks/blob/master/incubator/java-microprofile/image/project/Dockerfile):

COPY --chown=1001:0 --from=0 /config/ /config/

We did a test where we changed the Dockerfile to this and everything worked fine.

COPY --chown=1001:0 --from=0 /config/ /opt/ol/wlp/usr/servers/defaultServer/

Can the COPY step in the Dockerfile be updated to ^^ to avoid the kaniko bug?

**To Reproduce**
Run the java microprofile build task / pipeline located here:

https://github.com/kabanero-io/kabanero-pipelines/blob/master/pipelines/incubator/java-microprofile-pipelines/java-microprofile-build-task.yaml

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using: java-microprofile

**Screenshots**

**Additional context**

**Comment by gcharters** [comment]
/config is a symlink in the liberty images.  It makes moving between Open Liberty and WebSphere Liberty easier because it's just a change in the FROM.  If the suggested change is made it makes moving harder because the target dir will be different (/opt/ol vs /opt/wlp)

**Comment by stephenkinder** [comment]
@gcharters do you have an alternative FROM then?  We need a workaround for Kaniko builds of java-microprofile... the current FROM causes Kaniko (erroneously) to use the wrong server.xml, and the feature-set defined causes (among other issues) the mp-health feature to go walkabout.

We expect this workaround to be short-lived, as we are trying to move to a buildah format as well.

**Comment by kilnerm** [comment]
I have raised a PR that includes the proposed workaround....
https://github.com/kabanero-io/collections/pull/57

If an alternative solution is determined I can make the necessary changes but for now I assume we will release with the workaround.

**Comment by sympatheticmoose** [comment]
Issued has moved to kabanero
