### ISSUE TITLE
Microprofile: stack contains Jetty

### ISSUE THREAD

**Issue by ianpartridge** [appsody/stacks#305]
Automated scans of the Microprofile stack have found that it contains Jetty: 

```
/mvn/repository/org/mortbay/jetty/jetty-util/6.1.25/jetty-util-6.1.25.jar
/mvn/repository/org/mortbay/jetty/jetty/6.1.25/jetty-6.1.25.jar
```

This needs to be removed as the stack is based on OpenLiberty so Jetty should be unused and unnecessary.

**Comment by ianpartridge** [comment]
cc: @Emily-Jiang @neeraj-laad

**Comment by sympatheticmoose** [comment]
verified that it's not pulled in as part of this stack
