### ISSUE TITLE
[java-spring-boot2] No starter app on the default route! 

### ISSUE THREAD

**Issue by lroseblade** [appsody/stacks#31]
A more consumable experience post install would be to have a 'Welcome to appsody!' page on the default route. This gives confidence the install has completed successfully.

**Comment by ebullient** [comment]
We had the standard IBM Cloud landing page for apps.. do you want to resurrect / rebrand that?

**Comment by lroseblade** [comment]
As long as the user who has just installed appsody gets an obvious visual confirmation that the install has been successful then that's great. While the 404 page is technically correct as there is no app assigned to the route, it can also give an impression the install perhaps didn't fully complete.

The node stacks complete with a "Hello World!" page, which I think is also fine (although 'Welcome to appsody stacks') would probaby be better. Whichever page is chosen it should be consistent throughout all the stacks.

**Comment by seabaylea** [comment]
I think all we need is for `/` to respond with a simple "Hello from Appsody"/"Welcome from Appsody" so that a success is reported (rather than "Not Found" which might make people who are just evaluating the stack think that it's broken.

**Comment by barecode** [comment]
Proposed a small PR to make the default context root behave a little more user friendly - following @seabaylea 's recommendation. I've also created PRs #47 and #49 to make the Hello world response "Hello from Appsody!" so its clear that the response is coming from an Appsody stack.
