### ISSUE TITLE
Make the sample-stack executable by Appsody

### ISSUE THREAD

**Issue by henrynash** [appsody/stacks#310]
The sample stack has already been improved thanks to the work of @Kamran64 . What would make it even more useful is to allow it to be actually executable by Appsody (i.e. you can run/build/deploy it). This would allow a new stack developer to copy the sample stack, run it to provide that everything is set up OK, and then start modifying it.

In terms of the application could be just something like "echo" :-)

**Comment by neeraj-laad** [comment]
@henrynash Thanks for raising this. I like the idea of giving them a stack that can actually run, but thinking of what could be meaningful.  Can we make meaningful inclusions to the stack such that the stack developer does not have to delete things from the sample?

**Comment by henrynash** [comment]
That's what I tried to do in the commit. The only think you would change is replace the one-line hello.sh and test.sh with something that was relevant. My goal is that, in the docs, we can say:

1) Copy the sample tree (say into experimental, and rename to what you want)
2) Build and run it to make sure you have everything set up
3) Go start adding/changing

**Comment by henrynash** [comment]
After discussions, we decided to instead make an additional sample stack that covers this approach. This is raises as feature request #360, so closing this issue.
