### ISSUE TITLE
golang stack

### ISSUE THREAD

**Issue by qibobo** [appsody/stacks#340]

**Comment by qibobo** [comment]
@neeraj-laad 
I am willing to do the golang stack work. Could you provide some guide how I can create, build, test and release a stack?

**Comment by sympatheticmoose** [comment]
Hi @qibobo - thanks for showing an interest in this :) you can use the guidance here https://appsody.dev/docs/stacks/create as well as the sample stack https://github.com/appsody/stacks/tree/master/samples/sample-stack. We also have the 'stack_providers' channel in slack if you'd like to discuss more there.

**Comment by jpapejr** [comment]
I've developed two go-based stacks already and I've certainly willing to contribute them to the stack repo if that's what's desired.. Check them out by adding a new repo from [here](https://github.com/jpapejr/appsody-stacks/releases/download/latest/index.yaml).

**Comment by qibobo** [comment]
@jpapejr  thank you.

**Comment by jpapejr** [comment]
Just to make sure I'm looking at the right guidelines, would someone mind posting the stack submission requirements here pls?

**Comment by jpapejr** [comment]
Just submitted a PR for my two go stacks https://github.com/appsody/stacks/pull/425

**Comment by neeraj-laad** [comment]
Closing this issue as we have golang modules stack released and the PR for golang deps stack needs more re-work. PR has been inactive and closed. We can re-open the issue if this becomes active work again.
