### ISSUE TITLE
ci build scripts for a specific repo/stack seems to process all repos

### ISSUE THREAD

**Issue by henrynash** [appsody/stacks#354]
When trying to build a specific repo/stack, the build scrips seem to do a lot more...e.g.

$ ./ci/build.sh incubator/python-flask
 == Running pre_env.d scripts
 == Done pre_env.d scripts
~/go/src/github.com/appsody/stacks/ci/build/prefetch ~/go/src/github.com/appsody/stacks
== https://github.com/appsody/stacks/releases/latest/download/experimental-index.yaml
   https://github.com/appsody/stacks/releases/download/java-spring-boot2-liberty-v0.1.9/experimental.java-spring-boot2-liberty.v0.1.9.templates.default.tar.gz
   https://github.com/appsody/stacks/releases/download/nodejs-functions-v0.1.3/experimental.nodejs-functions.templates.simple.tar.gz
   https://github.com/appsody/stacks/releases/download/quarkus-v0.1.5/experimental.quarkus.v0.1.5.templates.default.tar.gz
   https://github.com/appsody/stacks/releases/download/vertx-v0.1.2/experimental.vertx.v0.1.2.templates.default.tar.gz
== https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml
   https://github.com/appsody/stacks/releases/download/java-microprofile-v0.2.14/incubator.java-microprofile.v0.2.14.templates.default.tar.gz
   https://github.com/appsody/stacks/releases/download/java-spring-boot2-v0.3.13/incubator.java-spring-boot2.v0.3.13.templates.default.tar.gz
   https://github.com/appsody/stacks/releases/download/java-spring-boot2-v0.3.13/incubator.java-spring-boot2.v0.3.13.templates.kotlin.tar.gz
   https://github.com/appsody/stacks/releases/download/nodejs-express-v0.2.6/incubator.nodejs-express.v0.2.6.templates.simple.tar.gz
   https://github.com/appsody/stacks/releases/download/nodejs-express-v0.2.6/incubator.nodejs-express.v0.2.6.templates.skaffold.tar.gz
   https://github.com/appsody/stacks/releases/download/nodejs-loopback-v0.1.4/incubator.nodejs-loopback.templates.scaffold.tar.gz
   https://github.com/appsody/stacks/releases/download/nodejs-v0.2.5/incubator.nodejs.templates.simple.tar.gz
   https://github.com/appsody/stacks/releases/download/python-flask-v0.1.3/incubator.python-flask.v0.1.3.templates.simple.tar.gz
   https://github.com/appsody/stacks/releases/download/swift-v0.1.4/incubator.swift.templates.simple.tar.gz
== https://github.com/appsody/stacks/releases/latest/download/stable-index.yaml
~/go/src/github.com/appsody/stacks

**Comment by ebullient** [comment]
Prefetch will fetch the latest templates for all stacks to stuff them into the assets dir for build and update or validation later. It's a straight-up crawl/fetch/dump. Not much analysis done. This is used when creating the non-local (but still usable) indexes during package.sh. The templates are also all included together in the usable index image.

**Comment by henrynash** [comment]
That was an excellent description of what is happening :-) However, I guess my question is why do we need to do this? What if I was running offline (or in an air gapped environment)? How could I "just build my local stack into a local stack repo"?

**Comment by neeraj-laad** [comment]
I agree with @henrynash. while doing this for the appsody CI and allowing other projects to be able to build these, we have made the process more complex for an appsody stack developer who just wants to build and test his single stack.. Perhaps we can disable PREFETCH steps, for the local use case and do those only in Travis?

**Comment by Kamran64** [comment]
@henrynash @ebullient 

Currently working on something for this. After talking to @neeraj-laad, would it better if the prefetch step is optional for the user when building locally (maybe some kind of argument passed in) and mandatory for the travis build? I've started on some implementation where repo indexes will only be generated for stacks the user is building locally i.e. no need to generate an ```experimental-local-index.yaml``` when the user is only building incubator stacks. 

Let me know what you both think :)

**Comment by ebullient** [comment]
Just use an environment variable, with a default off/false value.

Enable for Travis build:
https://github.com/appsody/stacks/blob/eca1ff7f06fb4457d11a10ad05041abb48ca011d/ci/ext/pre_env.d/10_travis#L11

00_local files are already ignored to tweak local behavior

**Comment by henrynash** [comment]
My view is that we should try and do what the user is asking for and no more. If I do a stack build for a particular stack, I would expect it to do "just enough" to execute that build. I would actually question whether, for stack development, we even want to go and run the current test.sh as part of this....I am just asking ci to build my stack.

**Comment by nastacio** [comment]
Does this issue still make sense after the inclusion of the `appsody stack package` command?

**Comment by neeraj-laad** [comment]
I think we should close this issue. We will make further improvements to `appsody stack package` and `appsody stack validate` commands (if needed). 

We are also looking to use those commands in the ci scripts so we do the exact same thing for local and ci builds - https://github.com/appsody/stacks/issues/422
