### ISSUE TITLE
Question:  ON_CHANGE kill for nodejs-loopback leaves zombie processes if done quickly

### ISSUE THREAD

**Issue by kewegner** [appsody/stacks#359]
If I touch a file multiple times very quickly I get this error:[Container] Error: Cannot find module './dist'
[Container]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[Container]     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
[Container]     at Module.require (internal/modules/cjs/loader.js:692:17)
[Container]     at require (internal/modules/cjs/helpers.js:25:18)
[Container]     at Object.<anonymous> (/project/user-app/index.js:1:21)
[Container]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[Container]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Container]     at Module.load (internal/modules/cjs/loader.js:653:32)
[Container]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[Container]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Container]     at Module.require (internal/modules/cjs/loader.js:692:17)
[Container]     at require (internal/modules/cjs/helpers.js:25:18)
[Container]     at Object.<anonymous> (/project/src/index.ts:12:17)
[Container]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[Container]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[Container]     at Module.load (internal/modules/cjs/loader.js:653:32)
[Container] npm ERR! code ELIFECYCLE
[Container] npm ERR! errno 1
[Container] npm ERR! nodejs-loopback@0.1.4 start: `node -r source-map-support/register .`
[Container] npm ERR! Exit status 1
[Container] npm ERR! 
[Container] npm ERR! Failed at the nodejs-loopback@0.1.4 start script.
[Container] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[Container] 

[Container] npm ERR! A complete log of this run can be found in:
[Container] npm ERR!     /root/.npm/_logs/2019-09-17T15_04_27_330Z-debug.log
[Container] [Warning] Wait Received error starting process of type APPSODY_RUN/DEBUG/TEST_ON_CHANGE while running command: npm run pretest --prefix user-app && npm start error received was: exit status 1

``

This does not happen for nodejs-express for instance.

Can you give us any insight as to this error.

**Comment by neeraj-laad** [comment]
@raymondfeng you might be best placed to answer this..

The big difference in my mind between the two stacks is the typescript compilation step.

**Comment by neeraj-laad** [comment]
No one has ever reported this issue. Closing this for now. Can re-open if this really is a problem
