### ISSUE TITLE
ci build script randomly removes all repos from appsody repo list

### ISSUE THREAD

**Issue by Kamran64** [appsody/stacks#368]
**Describe the bug**
Sometimes when running the build script, the script will exit with the error:
```[Error] Your stack repository is empty - please use `appsody repo add` to add a repository.
Unable to initialize project
Finished with 1 error(s) ```

Following this, running ```appsody repo list``` reveals that all repos have been removed, like so:
![Screenshot 2019-09-20 at 11 06 41](https://user-images.githubusercontent.com/45264227/65319121-d2d0fe00-db96-11e9-8031-63a47e825d1f.png)

**To Reproduce**
1. Run ```appsody repo list```to see all repos
2. Run the build script with any stack (I was building microprofile and vertx)
3. Run ```appsody repo list``` again to see all repos removed.

Again, for me this happens randomly so I'm not sure exactly what is triggering it (but I've encountered it several times this morning both on my own branch and master)

**Expected behavior**
The build script should finish and the relevant repos added.

**Actual behaviour**
Repos being removed

**Environment Details (please complete the following information):**
 - OS: macOS
 - Version: 10.14.6

**If applicable please specify:**
 - CLI version: 0.4.5

**Screenshots**

**Additional context**
@skoh7645 also encountered this problem.

Temporary fix is to run: ```rm -rf ~/.appsody``` to reset the repos to just ```appsodyhub``` and ```experimental``` followed by running the build script again.

**Comment by kylegc** [comment]
I believe Erin is working on this, moving to In Progress

**Comment by ebullient** [comment]
yes. I am.  Thanks, @kylegc

**Comment by kylegc** [comment]
@ebullient any progress on this? I've seen this behavior a few times recently too.

**Comment by neeraj-laad** [comment]
This should not be resolved as the CI scripts are not adding/removing repos.
