### ISSUE TITLE
Images created based on java-spring-boot2 stack have vulnerability warnings

### ISSUE THREAD

**Issue by GregDritschler** [appsody/stacks#372]
**Describe the bug**
Vulnerability Advisor reports warnings on images created based on java-spring-boot2 stack

**To Reproduce**
Run IBM Vulnerability Advisor on any application image created from the java-spring-boot2 stack

**Expected behavior**
No vulnerability warnings

**Actual behaviour**
Many vulnerability warnings

**Environment Details (please complete the following information):**
 - OS: Windows 10

**If applicable please specify:**
 - CLI version: 0.4.2
 - Stack you are using: java-spring-boot2

**Screenshots**

**Additional context**
The Dockerfile in the java-spring-boot2 stack runs `apt-get update` in the compile stage but not in the final run stage.  Contrast this with the nodejs-express stack which runs `apt-get update` in both stages.  I have not looked into whether other stacks might have this problem.

**Comment by ebullient** [comment]
This will be resolved by #325

**Comment by Kamran64** [comment]
@ebullient can this now be closed since #325 was merged?

**Comment by neeraj-laad** [comment]
@GregDritschler We believe this should be resolved in the latest stack release. Are you able to verify that using IBM Vulnerability Advisor?

**Comment by GregDritschler** [comment]
Yes it is fixed.
