### ISSUE TITLE
Node.js Functions Stack is not able to manage functions that are not exported as GET

### ISSUE THREAD

**Issue by frandai** [appsody/stacks#384]
**Describe the bug**
Node.js Functions Stack (experimental/nodejs-functions) is only compatible with GET HTTP methods. The stack is not able to use the functions that doesn't use the GET method.

**To Reproduce**
1. Init the stack: `appsody init expermiental/nodejs-functions`
2. Create a function that doesn't use the default GET HTTTP method:
```javascript
module.exports.url = '/method'
module.exports.put = function(req, res, next) {
    res.send('Hello from Appsody!')
}
```
3. Start the stack `appsody start`

**Expected behavior**
When the endpoint method is called using the PUT HTTP request method it should return the message 'Helo from Appsody!'
For example:
```bash
curl -XPUT http://localhost:3000/method
```
Should return *Hello from Appsody!*

**Actual behaviour**
The method returns a 404 not found error with the message: *Cannot PUT /method*

**Environment Details (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: curl 7.54.0
 - Version 7.54.0

**If applicable please specify:**
 - CLI version: appsody 0.4.5
 - Stack you are using (including the version): expermiental/nodejs-functions 0.1.3 simple

**Additional context**
We think the problem is in *experimental/nodejs-functions/image/project/server.js*

In this piece of code:
```javascript
  if (exports.put != undefined) app.put(exports.url, exports.get); return;
  if (exports.post != undefined) app.post(exports.url, exports.get); return;
  if (exports.patch != undefined) app.patch(exports.url, exports.get); return;
  if (exports.delete != undefined) app.delete(exports.url, exports.get); return;
  if (exports.head != undefined) app.head(exports.url, exports.get); return;
  if (exports.options != undefined) app.options(exports.url, exports.get); return;
  if (exports.connect != undefined) app.connect(exports.url, exports.get); return;
  if (exports.trace != undefined) app.trace(exports.url, exports.get); return;
  if (exports.all != undefined) app.all(exports.url, exports.get); return;
```

The exported method that is trying to be applied to "app" is always the exported *get* method, but it should be the exported method that is used for each method. For example: `if (exports.put != undefined) app.put(exports.url, exports.get); return;` should be `if (exports.put != undefined) app.put(exports.url, exports.put); return;`

**Comment by neeraj-laad** [comment]
Changes make sense, however, I was not able to get the use case described above working. @Kamran64 Please can you try the same, perhaps I'm missing something here.

**Comment by frandai** [comment]
Hi, the "return" statement was called just after the 1st if (the GET method), making the rest of the code unreachable. Please check the new commit in the PR where I have fixed it.
