### ISSUE TITLE
ci build script randomly exits when testing appsody build

### ISSUE THREAD

**Issue by Kamran64** [appsody/stacks#390]
**Describe the bug**
When running the build script, sometimes during the ```test``` phase, specifically ```appsody build``` the build will freeze and become unresponsive. This causes Travis builds to "error out" forcing a restart. (Testing locally you can Ctrl-C to exit and re run)

**To Reproduce**
1. Run the build script locally
2. See: ``` > appsody build``` freeze
3. On Travis: See the build error out.
    Locally: See the build freeze forcing you to Ctrl-C and restart.

**Expected behavior**
Build script should finish successfully 

**Actual behaviour**
Build script freezes locally and errors out on Travis due to no response

**Comment by neeraj-laad** [comment]
This should be resolved now as we have re-implemented a different way to build and test stacks
