### ISSUE TITLE
Update template app-config.yaml files with `monitoring` support

### ISSUE THREAD

**Issue by seabaylea** [appsody/stacks#391]
**Is your feature request related to a problem? Please describe.**
The Appsody-operator now supports creating ServiceMonitor CRs for deployed applications if there is a `spec.monitoring` entry in the AppsodyApplication CR:
https://github.com/appsody/appsody-operator/pull/125

This is used to register the application with Prometheus for cases where Prometheus has been deployed using the Prometheus operator rather than the Prometheus helm chart.

**Describe the solution you'd like**
For the stacks that support Prometheus and have the current `prometheus.io/scrape: 'true'` annotation, **also** use `spec.monitoring` so that the correct ServiceMonitor CR can be created.

**Describe alternatives you've considered**

**Additional context**

**Comment by Kamran64** [comment]
Making a list of stacks that currently support Prometheus to tick off as added:
- [ ] Java Microprofile
- [ ] Java Spring Boot 2
- [ ] Java Spring Boot with Liberty
- [ ] Node.js Express
- [ ] Node.js Functions
- [ ] Python Flask

**Comment by seabaylea** [comment]
Note that, because the java-microprofile endpoint is authenticated, the config is slightly different for that stack.

**Comment by ebullient** [comment]
The current attempt for Spring Boot (vanilla) isn't right. Please work with @BarDweller to get the correct implementation for Spring.

**Comment by Kamran64** [comment]
Reopened a few PR's after some more testing (and figuring out how some of it works) 

@ebullient - I left the ones on Spring + Spring with Liberty closed for now as I know you and @BarDweller wanted a different approach.

**Comment by Kamran64** [comment]
Closing this issue - I've raised separate issues for stacks that still do not support this feature
