### ISSUE TITLE
Appsody CI sets up some repositories for testing but doesnt remove them

### ISSUE THREAD

**Issue by groeges** [appsody/stacks#392]
**Describe the bug**
When running a local appsody build './ci/build.sh' the test phase (test.sh) adds the built indexes to the appsody repo list in order to be able to init and build the stacks. However, these are not removed at the end of the test phase. If these repos have already been added from an earlier build they are not added again but just reused. This causes issues on a local build if different builds are done that use different git repositories, ie with different content. 
 
**Expected behavior**
The appsody configuration should be the same after the build as it was prior tot he build.

**Actual behaviour**
The appsody config is updated to point to the local indexes.

**Comment by neeraj-laad** [comment]
@groeges does this become invalid after the CI scripts start using the appsody stack validate command?

**Comment by groeges** [comment]
Yes. The only repository that gets added is `dev.local`.  
I don't think that causes any issues so it is OK that this repository gets added and doesn't get removed.
Will close this issue.
