### ISSUE TITLE
Define the structure of the readme for Appsody stacks

### ISSUE THREAD

**Issue by chilanti** [appsody/stacks#40]
Define the headers and describe the expected content. 
For instance:
* Introduction
-- What the stack is all about
-- Getting started info

* Use cases and expected behavior
-- Developing and debugging 
-- Technical details (exposed ports, mount points...)
-- Dependency management

* Troubleshooting and Known issues

**Comment by neeraj-laad** [comment]
I think this seems like a reasonable structure, we need a linter to enforce this now.
