### ISSUE TITLE
appsody build on java-spring-boot2 fails if using appsody package

### ISSUE THREAD

**Issue by tnixa** [appsody/stacks#408]
**Describe the bug**
If I build the stack using `appsody package` and then do a `appsody build` I get an error about not being able to create the maven repository. I think this is due to the `image/project/Dockerfile` using an env var in `FROM {{APPSODY_STACK}} as compile` which does not get set during `appsody package` so an old version is getting used.

```
[Docker] Sending build context to Docker daemon  596.5kB
[Docker] Step 1/16 : FROM appsody/java-spring-boot2:0.1 as compile
[Docker]  ---> d9288e1ad4de
[Docker] Step 2/16 : COPY . /project
[Docker]  ---> 71270b686da4
[Docker] Step 3/16 : WORKDIR /project/user-app
[Docker]  ---> Running in 6c59b0ef81f6
[Docker] Removing intermediate container 6c59b0ef81f6
[Docker]  ---> 935b84067d35
[Docker] Step 4/16 : RUN /project/util/check_version build  && /project/java-spring-boot2-build.sh package
[Docker]  ---> Running in ce629a4f96e4
[Docker] Could not find local Maven repository
[Docker] 
[Docker]     Create a .m2/repository directory in your home directory. For example:
[Docker]     * linux:   mkdir -p ~/.m2/repository
epository    * windows: mkdir %SystemDrive%%HOMEPATH%\.m2
[Docker]     
[Docker] The command '/bin/sh -c /project/util/check_version build  && /project/java-spring-boot2-build.sh package' returned a non-zero code: 1
[Error] exit status 1
```

**To Reproduce**
1. From the root directory of the stack ex: `incubator/java-srping-boot2` run `appsody stack validate`
This will perform several steps including `appsody stack package` and `appsody build` and the `appsody build` will fail...

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu

**If applicable please specify:**
 - CLI version: 0.4.6
 - Stack you are using (including the version): java-spring-boot2

**Comment by tnixa** [comment]
@BarDweller might be able to help..

**Comment by BarDweller** [comment]
Daft question.. where is `appsody package` (or indeed `appsody stack
package`) documented? It's not on the official doc page at
https://appsody.dev/docs/using-appsody/cli-commands/, so I'm a little left
guessing what it's supposed to do.

Hard to support a use case the stack is unaware of!

**Comment by ebullient** [comment]
This is a bug in the new CLI command, @tnixa  -- it needs to pass in what the package script currently is.

**Comment by tnixa** [comment]
will discuss with @neeraj-laad

**Comment by BarDweller** [comment]
@neeraj-laad any progress on this one? I'm seeing more discussion of `appsody stack package` and if it can't emulate the existing packaging behavior, it prevents downstream consumers of the spring stacks from being able to fork, customise & build their own derivatives.

**Comment by ebullient** [comment]
Closing this, as I think it's covered by the CI scripts item. This isn't a bug w/ the Spring stack, it's a requirement for templating support. ;)
