### ISSUE TITLE
Automated build for Appsody stacks

### ISSUE THREAD

**Issue by kylegc** [appsody/stacks#41]
- create and run linters (file structure, Knapp watcher, config, env variables etc.)
- incremental build for the platforms (docker images) 
- incremental build for the templates (tar files)
- incrementally invoking tests all platform and templates
- creating a catalog (index.yaml) with all platforms and templates available
- publish the index.yaml for CLI to consume
- Update the website (if not pulled in automatically)

**Comment by neeraj-laad** [comment]
this is complete now,e except for linters, which are low-priority at this point in time.
