### ISSUE TITLE
Automated test suite for Appsody stacks

### ISSUE THREAD

**Issue by kylegc** [appsody/stacks#42]
We need to have tests for each stack and template

We could possibly need Champs to be able to run this while developing the platform.

We might want to run these tests on:
- A template
- A stack (and all it's templates)
- All stacks (and all their templates)

The test suite should do the following:
- appsody run - The container comes up and responds to health and readiness endpoints
- appsody test - runs platform / app tests complete successfully
- appsody debug - The container comes up and responds to health and readiness endpoints + port??
- appsody build - build completes successfully (optional check health on the image)

**Comment by tnixa** [comment]
Some thoughts on this topic...
# High Level
## Platforms
- Run stacks in all supported OS platforms (OSX, RHEL, Ubuntu, Windows)
## CLI
- init, run, test, debug, stop
## Web
- verify sample endpoints
## Code
- make valid code change and verify endpoint reflects the change
- make invalid code change and verify compile error and graceful exit
- fix invalid code change and verify endpoint reflects the change
- do a run with existing invalid code change and verify proper error message and graceful exit

# Details
## Platforms
- Run stack tests in all supported OS platforms:
  - OSX
  - RHEL
  - Ubuntu
  - Windows
  - Do we need to be concerned about different OS levels/versions?
## CLI
- init:
  - try from empty directory
  - try from non-empty directory
  - try with invalid stack name
- run: 
  - try from invalid directory
  - try from valid directory
- test:
- debug:
- stop
  - try from invalid directory
  - try from valid directory
  - try Ctrl-c instead
## Web
- Endpoints
  - Java Microprofile:
    - Health endpoint: http://localhost:9080/health
    - Metrics endpoint: http://localhost:9080/metrics (login as `admin` user with `adminpwd` password)
    - OpenAPI endpoint: http://localhost:9080/openapi
    - Swagger UI endpoint: http://localhost:9080/openapi/ui
  - Spring Boot 2:
    - Health endpoint: http://localhost:8080/actuator/health
    - Liveness endpoint: http://localhost:8080/actuator/liveness
    - Metrics endpoint: http://localhost:8080/actuator/metrics
    - Prometheus endpoint: http://localhost:8080/actuator/prometheus
  - Node.js Express
    - Readiness endpoint: http://localhost:3000/ready
    - Liveness endpoint: http://localhost:3000/live
    - Health check endpoint: http://localhost:3000/health
## Console
  - Node.js:
    - no web endpoint so need to check for "Hello" message
## Code
- Node.js
  - app.js
    - make valid code change and verify endpoint reflects the change
    - make invalid code change and verify compile error and graceful exit
    - fix invalid code change and verify endpoint reflects the change
    - do a run with existing invalid code change and verify proper error message and graceful exit
  - other files to change/test?
- Node.js Express
  - app.js
    - make valid code change and verify endpoint reflects the change
    - make invalid code change and verify compile error and graceful exit
    - fix invalid code change and verify endpoint reflects the change
    - do a run with existing invalid code change and verify proper error message and graceful exit
  - other files to change/test?
- Java Microprofile
  - src/main/java/dev/appsody/starter/health/StarterHealth.java
    - make valid code change and verify endpoint reflects the change
    - make invalid code change and verify compile error and graceful exit
    - fix invalid code change and verify endpoint reflects the change
    - do a run with existing invalid code change and verify proper error message and graceful exit
  - other files to change/test?
- Spring
  - src/main/java/application/Main.java
    - make valid code change and verify endpoint reflects the change
    - make invalid code change and verify compile error and graceful exit
    - fix invalid code change and verify endpoint reflects the change
    - do a run with existing invalid code change and verify proper error message and graceful exit
  - other files to change/test?

# Test Frameworks
## Travis
- What scenarios/environments can Travis not cover?
  - Web endpoint checking capability?

# Test Environments
## Travis
- What scenarios/environments can Travis not cover?
  - Issues with OSX and Windows?
## Systems
- Do we need to request dedicated test systems/images/VMs?
  - Can we leverage Softlayer?
## IDE
- Do we need to verify code changes using various IDEs: VI, VSCode, Eclipse...?
