### ISSUE TITLE
Create Python-Flask stack

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#43]
We need to have an Appsody stack that allows users to create Python-Flask based applications.

**Comment by neeraj-laad** [comment]
@seabaylea has done initial investigation on this stack. It would be good to take that work forward and get it to an incubator state.

**Comment by bharathappali** [comment]
Flask's built in server is not a good choice for production env, So can this stack house any webserver like ngnix ?

**Comment by henrynash** [comment]
@bharathappali regarding nginx, once we have my new PR merged in incubator, I'll investigate this. As an aside, Flask does allow you to swap out its developer engine for something like nginx, so this *should* be possible.
