### ISSUE TITLE
Explore possibility to access stack metadata within the stack

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#430]
Today we have to hard code the key information (name, version etc.) about a stack in multiple places within the stack. It would be great if these values were available for stack creators to use within the files of the stack (image + template). 

Users could use these values in various build config files (pom.xml, package.json) but could also provide more meaningful welcome messages stating what stack and version they are running etc.

stack.yaml will be the place where all the useful information is captured, while other places will have references to this. These references could be translated into real values before the stack is built (docker image + template archive) and published.

One approach could be in `appsody stack package` command and use some go templating library. 

This issue is purely to explore this idea and capture findings. pros and cons etc. If we agree to implement this we'll create a separate issue for it.

**Comment by CameronMcWilliam** [comment]
# Update on Issue

## Method

* Would be called in `appsody stack package` command
* Use built in Go `text/template` package
* Pull values from `stack.yaml` file into a `metadata`
* `filepath.Walk` through directory we want to template
* Copy file into target directory, preserving file structure and permissions
* Check if file is read only, if read only, set to write only temporarily
* Create new template from file by using `ParseFiles` on file
* Open target copied file and `ExecuteTemplate` using `metadata` object
* Close file and if originally read only, set back to read only

## Further details

* Need to discuss exactly what metadata we want.
* If a user wants to use templating they can wrap their variable as so:
```
{{"{{.UserVariableName}}"}}
```
> This could be avoided by using custom Delimiters

* Current method applies template to entire project, could make stack creator declare a pre defined array of files that need templating as to avoid any unwanted templating.  This however, means more work for stack creator.

**Comment by BarDweller** [comment]
The spring stacks are already making use of metadata passed to the stack during package as args. (Although `appsody stack package` has an open bug against it #408 where it's failing to pass these). 

We're currently doing homegrown var substitution using sed as part of our stack, the provision of a standardised templating feature for stack templates could be interesting, and we could migrate to it if it offered a better way to do things. (at the risk of stack.yaml starting to feel a bit like a helm chart).

I'm assuming here that appsody would expose some items for use as values that are not in `stack.yaml`, eg, appsody version, build date, build time etc would be useful to template in, although they are not strictly 'stack metadata' (and certainly do not come from `stack.yaml`)

Would placeholder resolution only occur at stack build time? is there scope for further resolution as a template is unpacked on a dev system (eg. during `appsody init` ). For Java, something like that could hypothetically allow the correct mapping for the users configured maven cache to become part of the appsody mount list.

**Comment by neeraj-laad** [comment]
@BarDweller The intent is to explore possibility of providing standard templating capability so stack creators do not have to do it themselves. They'll be able to use these template variables anywhere in the stack directory (image + template). This will be translated into real values before the stack is built.

@CameronMcWilliam Can you please post a draft list of variables here so we can refine and agree on those? 

The point regarding doing this resolution during init is interesting. I had not thought about this but could be something we can look at as a second pass on this if people find this useful.

**Comment by CameronMcWilliam** [comment]
Currently I only have `name` and `version` as variables, but it's easy to add more, we could include `description`, `language`, `template`. There should be further discussion on what we want to add.  Like I said it's simple to add more, however for the draft PR I will keep it as simply the `name` and `version`.  Unless there are serious objections.

**Comment by BarDweller** [comment]
I'd love for some sort of timestamp to be added to that, it would make differentiating between stacks in the wild that little bit easier.. suggest yyyymmddhhmmss format. Would give stack developers an easy way to know if the version they are running with IS actually the one they just built (assuming they are iterating changes to a given stack version), as well as a cheap way to confirm problem reports are against the official timestamp built version of the stack version. 

The Spring stack is currently consuming
Git Organisation, eg. `appsody/stacks`
Image Registry Org, eg. `appsody`
Stack Id, eg. `java-spring-boot2` (is this what you refer to as `name` ?)
Stack version, passed as Major/Minor/Patch separately.

**Comment by CameronMcWilliam** [comment]
Sure! I can look into adding the timestamp and other things now, I've created a [draft PR](https://github.com/appsody/appsody/pull/528) where I'll be adjusting things to feedback and of course fixing all my errors...

**Comment by neeraj-laad** [comment]
Closing this issue as we have some initial investigation is done and a prototype that looks promising. 

Now, we need to finalise the exact template values that we'll provide to stack creators and implement this capability as part of appsody stack package command. Have raised an issue #457 for that.
