### ISSUE TITLE
Java-MicroProfile: Required "paths" field is missing

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#44]
when i run microprofile i am noticing the following error...
```
[Container] [INFO] [ERROR   ] CWWKO1650E: Validation of the OpenAPI document produced the following error(s):
[Container] [INFO]
[Container] [INFO]  - Message: Required "paths" field is missing or is set to an invalid value, Location: #
[Container] [INFO]
[Container] [INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://2f00029ff319:9080/
[Container] [INFO] [AUDIT   ] CWWKZ0001I: Application starter-app started in 3.046 seconds.
[Container] [INFO] [AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonb-1.0, jsonp-1.1, jwt-1.0, microProfile-2.2, mpConfig-1.3, mpFaultTolerance-2.0, mpHealth-1.0, mpJwt-1.1, mpMetrics-1.1, mpOpenAPI-1.1, mpOpenTracing-1.3, mpRestClient-1.2, opentracing-1.3, servlet-4.0, ssl-1.0].
[Container] [INFO] [AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 14.130 seconds.
```
I am still able to access the endpoint despite the error so I don't think its a critical error.

**Comment by neeraj-laad** [comment]
@Emily-Jiang Would like to know your thoughts on this issue

**Comment by neeraj-laad** [comment]
this is not really an appsody issue. It is how microprofile deals with OpenAPI where no resources are defined. We do not want to define resources and have users delete it.

**Comment by ykoyfman** [comment]
Hi @Emily-Jiang Just ran into this myself running the MicroProfile stack.  What about having an "example" resource as part of the template that's clearly labeled as such?

**Comment by arthurdm** [comment]
hi @neeraj-laad - can you please clarify which endpoint you are referring to in terms of being accessible?  

Endpoints such as `/health` and `/openapi` are from Liberty itself, not the app.   This error is saying that the application is not exposing any endpoints, which seems to be true.

**Comment by arthurdm** [comment]
Since every app will need at least the 1 resource, then I think it's reasonable to ship a template that has 1 resource, so the user can easily customize it, instead of creating it from scratch.

CC @Emily-Jiang / @seabaylea
