### ISSUE TITLE
nodejs: appsody run with the nodejs stack does not work with Socket.IO

### ISSUE THREAD

**Issue by andrewhughes101** [appsody/stacks#447]
**Describe the bug**
When using an express and Socket.IO app appsody run throws the following error.

```
Error: Can't set headers after they are sent.
[Container]     at SendStream.headersAlreadySent (/project/user-app/node_modules/send/index.js:390:13)
[Container]     at SendStream.send (/project/user-app/node_modules/send/index.js:617:10)
[Container]     at onstat (/project/user-app/node_modules/send/index.js:729:10)
[Container]     at /project/node_modules/async-listener/glue.js:188:31
[Container]     at FSReqWrap.oncomplete (fs.js:154:5)
```

Interestingly appsody build and then a docker run seems to work and not throw the above error.

**To Reproduce**
1. Clone the [repo](https://github.com/andrewhughes101/socketTest)
2. appsody init nodejs none
3. appsody run
4. see error

**Environment Details (please complete the following information):**
 - OS: macOS Catalina 10.15
 - Version: appsody 0.4.7, docker 19.03.4 
 - Stack you are using (including the version): nodejs 0.2.5

**Screenshots**
<img width="652" alt="Screenshot 2019-10-25 at 11 28 01" src="https://user-images.githubusercontent.com/38461805/67565106-89874780-f71c-11e9-9398-214394ce78bf.png">

**Additional context**
A seperate docker build and docker run using the Dockerfile in the repo also seems to work

**Comment by sam-github** [comment]
@neeraj-laad FYI, I'm near to PRing a fix for this.
