### ISSUE TITLE
Java-MicroProfile: stack should only watch certain files for changes

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#45]
The current stack is configured to watch for changes to /src folder, does a `mvn compile` when a change i detected. Perhaps we can also filter the types of files we look for. E.g: only watch for changes to .java file. 

Would it make sense to watch for changes to .xml files, for pom and server.xml changes?

**Comment by neeraj-laad** [comment]
@Emily-Jiang Would like to know your thoughts on this issue.

**Comment by Emily-Jiang** [comment]
It is good to watch on .xml, .properties, server.xml file changes.
