### ISSUE TITLE
python-flask deploy endpoint not reachable

### ISSUE THREAD

**Issue by tnixa** [appsody/stacks#461]
**Describe the bug**
Trying an `appsody deploy` of the python-flask stack and the endpoint is not reachable

**To Reproduce**
1. setup and configure docker desktop with kubernetes
2. `mkdir python-flask`
3. `cd python-flask`
4. `appsody init python-flask`
5. `appsody deploy -v`

**Expected behavior**
Expected to get the usual endpoint webpage

**Actual behaviour**
The endpoint URL given `http://localhost:31867` is not reachable
```
[Docker] Successfully built 4911c055ac6c
[Docker] Successfully tagged dev.local/python-flask:latest
Built docker image dev.local/python-flask
Using applicationImage of: dev.local/python-flask
Attempting to apply resource in Kubernetes ...
Running command: kubectl apply -f app-deploy.yaml --namespace test
Deployment succeeded.
Appsody Deployment name is: python-flask
Running command: kubectl get rt python-flask -o jsonpath="{.status.url}" --namespace test
Attempting to get resource from Kubernetes ...
Running command: kubectl get route python-flask -o jsonpath={.status.ingress[0].host} --namespace test
Attempting to get resource from Kubernetes ...
Running command: kubectl get svc python-flask -o jsonpath=http://{.status.loadBalancer.ingress[0].hostname}:{.spec.ports[0].nodePort} --namespace test
Deployed project running at http://localhost:31867
```

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] mac, tried windows10 also

**If applicable please specify:**
 - CLI version: 0.4.8
 - Stack you are using (including the version): python-flask

**Screenshots**

**Additional context**

**Comment by skoh7645** [comment]
This happened to me too - it seemed to fix itself after I reset my Kubernetes cluster though...

**Comment by henrynash** [comment]
I'll investigate this to see if I can work out what is going on...

**Comment by henrynash** [comment]
The PR #475 contains a workaround fix for the problem, while I have raised as separate issue for the underlying problem
