### ISSUE TITLE
Appsody stack and Istio service mesh

### ISSUE THREAD

**Issue by chainhead** [appsody/stacks#476]
## Relationship between an Appsody stack and Istio service mesh

My goal is to run NodeJS based APIs in a service mesh - Istio. I have the following questions.

1. How do the endpoints exposed by Appsody compare with the [Istio metrics](https://istio.io/docs/concepts/observability/#metrics) ?

2. Given that, Istio works by injecting a [sidecar](https://istio.io/docs/reference/config/networking/v1alpha3/sidecar/), would all the endpoints (exposed by Appsody) run behind and be load-balanced by Istio?

**Comment by neeraj-laad** [comment]
Appsody doe nothing special with respect to deploying app or exposing endpoints. Can you please explain what your environment is and what you are trying to achieve?

**Comment by neeraj-laad** [comment]
closing this due to lack of response. Please feel free to re-open
