### ISSUE TITLE
Update java-microprofile stack to allow mpReactiveMessaging

### ISSUE THREAD

**Issue by Emily-Jiang** [appsody/stacks#477]
As mpReactiveMessaging-1.0 and mpContextPropagation features are not part of MicroProfile umbrella release. Only specifying microProfile-3.0 alone does not bring in these 2 features. I would like to expose APIs supported by these features. Therefore, the server.xml and pom.xml will need to be updated. Since these features are in later Liberty release, this issue will require to bring in Liberty 19.0.0.11.

**Comment by Emily-Jiang** [comment]
I'll propose a PR soon.

**Comment by scottkurz** [comment]
I think for enhancements like this we'd be more likely to consider for the new **java-openliberty** stack than the older **java-microprofile** stack (so I'm relabeling).

@Emily-Jiang were you thinking this would be used in a new template?  Or suggesting this should be part of the default template?

**Comment by scottkurz** [comment]
@matthewpwilson  (can't officially "assign" you though).
