### ISSUE TITLE
appsody build of java-microprofile hangs

### ISSUE THREAD

**Issue by tnixa** [appsody/stacks#479]
**Describe the bug**
I'm running `appsody build` of the java-microprofile stack and the command does not complete. It hangs on the following command...
`Docker] Downloading from central: https://repo.maven.apache.org/maven2/io/openliberty/openliberty-runtime/19.0.0.8/openliberty-runtime-19.0.0.8.zip`
I've waited over an hour so far and it is still hung
See attached log for full output:
[java-microprofile-hang.log](https://github.com/appsody/stacks/files/3837814/java-microprofile-hang.log)

**To Reproduce**
1. `mkdir java-microprofile`
2. `cd java-microprofile`
3. `appsody init java-microprofile`
4. `appsody build`

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] mac

**If applicable please specify:**
 - CLI version: 0.4.9
 - Stack you are using (including the version): java-microprofile

**Comment by nastacio** [comment]
Is this recreatable?

It would be interesting to run `curl https://repo.maven.apache.org/maven2/io/openliberty/openliberty-runtime/19.0.0.8/openliberty-runtime-19.0.0.8.zip` while this is happening to rule out transient network issues.

**Comment by tnixa** [comment]
I tried a few things just now...
1. works: `curl -O https://repo.maven.apache.org/maven2/io/openliberty/openliberty-runtime/19.0.0.8/openliberty-runtime-19.0.0.8.zip`
2. works: `appsody build` -> docker shows 19 steps
3. hangs: `appsody stack validate` -> docker shows 32 steps during appsody build
4. restarted docker then tried `appsody stack validate` again but it still hangs

**Comment by scottkurz** [comment]
I think the root cause is likely that we need to do the `mvn -B`  (batch).. otherwise the download progress gets messed up.     I recreated, made this change, and it went away.

**Comment by Kamran64** [comment]
Thanks @scottkurz, this has been giving a few of us some headache since Friday.

FYI: @neeraj-laad @groeges @tnixa I just tried this also and the problem was fixed.
