### ISSUE TITLE
java-microprofile: /openapi/ui doesn't show my app's endpoints

### ISSUE THREAD

**Issue by navidsh** [appsody/stacks#482]
**Describe the bug**
During local dev, `/openapi/ui` doesn't show my app's endpoints. It only lists endpoints from `javametrics`.

Note: This is because `mpOpenAPI-1.1` feature only scans one jax-rs app. if there is more than one jax-rs app, it'll scan only one. And in this case, it picks `javametrics`. `mpOpenAPI-1.1` doesn't provide a way to specify which app to scan.

**To Reproduce**
1. `appsody init java-microprofile`
2. `appsody run`
3. Go to http://localhost:9080/openapi/ui

**Expected behavior**
Expected to see starter app's endpoints

**Actual behaviour**
Saw endpoints from `javametrics`

**If applicable please specify:**
 - CLI version: `0.4.10`
 - Stack you are using (including the version): `java-microprofile@0.2.18`

**Screenshots**
N/A

**Additional context**
N/A

**Comment by scottkurz** [comment]
@navidsh  you might want to try the java-openliberty stack, which is also based on Open Liberty but, because it doesn't use the `javametrics` instrumentation, does not use the second app.

(Unless you were in need of specific metrics, since at the moment, java-openliberty only uses MicroProfile metrics which to my understanding, only contains a subset of the `javametrics` info).

**Comment by navidsh** [comment]
Thanks @scottkurz. What are the main differences between the two stacks beside `javametrics`?

**Comment by scottkurz** [comment]
The main difference is that we moved from the 2.x to 3.x version of liberty-maven-plugin, allowing us to improve startup time (now <1 min, was >2 min).   In doing so, we also moved from using appsody's "watcher" to the plugin's watcher function which allows faster updates on changes.

**Comment by navidsh** [comment]
Thanks for the explanation. I assume at some point it will be part of Kabanero Collections?

**Comment by neeraj-laad** [comment]
@scottkurz @navidsh Is there still an issue that needs to be worked upon or can we close this?

**Comment by scottkurz** [comment]
We're not going to fix this. Closing
