### ISSUE TITLE
Update stacks to utilise setting minimum requirements

### ISSUE THREAD

**Issue by Kamran64** [appsody/stacks#493]
**Is your feature request related to a problem? Please describe.**
Now that https://github.com/appsody/appsody/pull/535 has been merged, we should update all stacks that use `chown` to utilise this functionality. This will prevent users with lower than required versions of Docker from encountering errors further down the development line. We can also replace references to `APPSODY_INSTALL` and use `APPSODY_PREP` instead.

**Describe the solution you'd like**
- Set requirements for `chown` stacks to `>= 17.09.0` for Docker
- Replace references to `APPSODY_INSTALL` with `APPSODY_PREP`
- Set requirements for the Appsody CLI to `>= 0.2.7` for stacks using `APPSODY_PREP`

**Comment by Kamran64** [comment]
Stacks that use `chown` - `docker-version: ">= 17.09.0"`
- [ ] Java-spring-boot2-liberty
- [ ] Quarkus
- [ ] Java-microprofile
- [ ] Nodes-express
- [ ] Nodejs-loopback
- [ ] Nodejs

**Comment by sam-github** [comment]
The cli also warns about APPSODY_PROJECT being missing.

**Comment by Kamran64** [comment]
This works been handled in all incubator stacks now (and all stacks that need a requirement i.e. ones that use chown). Closing.
