### ISSUE TITLE
Cannot use git-commit-id-plugin with java-microprofile stack

### ISSUE THREAD

**Issue by GregDritschler** [appsody/stacks#504]
**Is your feature request related to a problem? Please describe.**
I tried to use the git-commit-id-plugin maven plugin to capture git repo information in my java-microprofile project. It doesn't work because the project's .git folder is not mounted into the container.  The plugin needs this folder to work.

I am able to use git-commit-id-plugin in a java-spring-boot2 project because that stack mounts the entire project into the container so the .git folder is available.  I don't know why the java-microprofile stack doesn't work the same way.

From what I understand maven-git-commit-id-plugin is a popular maven plugin so I imagine others will eventually have this issue.

https://github.com/git-commit-id/maven-git-commit-id-plugin

**Describe the solution you'd like**
Change the way the java-microprofile stack mounts the user's project into the container so that side folders such as the .git folder are available.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by scottkurz** [comment]
We are currently working on some stack updates to use liberty-maven-plugin dev mode to watch for changes rather than appsody, which should make it easier to mount the whole directory, which would seem to solve this.

**Comment by scottkurz** [comment]
I'm going to close this as a special case of #554.   Though it's a valid issue in its own right, in practice we'll probably either fix the broader issue (solving this too) or not fix it at all.

Note the new java-openliberty, evolved from the earlier java-microprofile stack, should not have this issue (though I haven't tested personally).
