### ISSUE TITLE
java-microprofile: what server config artifacts should be copied into the deployment image?

### ISSUE THREAD

**Issue by scottkurz** [appsody/stacks#521]
## Summary

The current `appsody build` builds the entire **target** server config directory into the Docker image, via:

 `mv wlp/usr/servers/*/* /config/`

On the other hand, the updated ["getting started" guide](https://github.com/OpenLiberty/guide-getting-started/blob/master/finish/Dockerfile) only copies the **src** config directory, using:

> COPY --chown=1001:0 src/main/liberty/config/ /config/
> COPY --chown=1001:0 target/*.war /config/apps/

##  ADVANTAGES / DISADVANTAGES

By copying the target server config dir, we allow any config generation/merge done by the liberty-maven-plugin to take effect.  E.g. the merge of  POM properties, plugin config (inline and pointing to external files), -Dx=y..   

By copying the server config contents from src, we avoid an issue like:
https://github.com/appsody/stacks/issues/516
where a "local dev" config artifact like **server.env** gets built into the image, though it shouldn't.

As the resolution of #516 shows, a solution here is to use appsody commands to structure your local dev (`appsody run/test/debug`) differently.   But we still have to decide if this should be the user's responsibility.

----
Finally, I'm not sure what the overlap is precisely yet, but the issue https://github.com/appsody/stacks/issues/364 is also relevant.

**Comment by yeekangc** [comment]
Define and describe what artifacts are expected where too.  For example, dependency jars as noted in https://github.com/kabanero-io/docs/issues/181.

**Comment by nastacio** [comment]
There is a layered problem in here in that the stack actually uses `liberty/wlp` instead of `wlp` as the base directory for the server, so that `mv wlp/usr/servers/*/* /config/` is not really doing anything since there is nothing in "target/wlp/..." at the end of a build.

**Comment by nastacio** [comment]
<Deleted my comment from 30 minutes ago as it was not making the problem clear. I am still rewording it for clarity and collecting more precise path collections for the examples.>

**Comment by scottkurz** [comment]
Though this issue hasn't been solved in the java-microprofile stack, relabeling to the java-openliberty stack, which is where we will prioritize a solution.

**Comment by scottkurz** [comment]
# PROBLEM:     

How to get resource adapters and shared libraries into Docker image.


## ASSUMPTION:  
Shared libraries and resource adapters are dependencies of the current project

# SOLUTION - liberty-maven-plugin (LMP)

## Nearer term proposal

LMP dev mode detects `maven-dependency-plugin:copy/copy-dependencies` goal configs
and calls them at some point in the dev mode-internal sequence (not sure what we call it...a "lifecycle"?).  

Guessing this is easy enough to detect in the general case (e.g. incorporating parent POMs), if not restrict to easier pattern?

Possibly in liberty:run too??

## Possible future enhancement

From dependency, LMP generates config (jdbcDriver, possibly references via defaultDatasource) and copies into special locations (customizable maybe?).

Note the work on the https://github.com/MicroShed/boost[Boost plugin] did this for JDBC driver, (not shared libs).

## Near-term workaround

Launch dev mode after explicitly calling the copy goals, e.g.:

`mvn liberty:create dependency:copy@my-execution-1 ... liberty:dev`

(You might need to have some extra considerations like needing to create the server first as in this example.)

### Appsody

We could workaround this by introducing a workaround variable, e.g.:

`ENV APPSODY_RUN="... mvn $APPSODY_MVN_EXTRAS liberty:dev"`

and then propagating env vars via appsody through Docker like:

`appsody run --docker-options="--env APPSODY_MVN_EXTRAS=dependency:copy@my-execution-1`

## Docker 

From the Dockerfile perspective, while the stack has to pick one order for layering to minimize image sizes, it would be easy for Champ, etc. to tweak and use a different order.

```
 # Stage 2: Package Open Liberty image
 FROM open-liberty:kernel-java8-openj9

 # 2a) shared resources change the least-frequently  (* - see note below)
 COPY --chown=1001:0 --from=0 /shared/resources /opt/ol/wlp/usr/shared/

 # 2b) next copy shared library
 COPY --chown=1001:0 --from=0 /config/libs/ /config/

 # 2c) Server config, bootstrap.properties, and everything else
 COPY --chown=1001:0 --from=0 /config/ /config/

 # 2d) Changes to the application binary
 COPY --chown=1001:0 --from=0 /project/user-app/target/*.war /config/apps
```
 (*) Even for the one-app containerized server, carry forward the convention of using `usr/shared/resources`, since the special Liberty config property `shared.resource.dir` maps to it.
 Setup from Stage 1 not shown here.

**Comment by scottkurz** [comment]
See discussion in [LMP issue 705](https://github.com/OpenLiberty/ci.maven/issues/705).

**Comment by scottkurz** [comment]
While it would require some design and discussion to get consensus on including some but not other entries with the target Open Liberty install, as long as we continue just copying everything (what we are doing today), then there's not much value in keeping this issue open.  Closing.
