### ISSUE TITLE
appsody run and build failing.

### ISSUE THREAD

**Issue by shantr15** [appsody/stacks#524]
**Describe the bug**
I have created a new project using appsody init java-microprofile on my RHEL 7 system. 
Although appsody init works fine, appsody run fails withthe below error:

 [shanthir@oc7447002330 appsody-project]$ sudo appsody run
Running development environment...
Pulling docker image appsody/java-microprofile:0.2
Running command: docker pull appsody/java-microprofile:0.2
Trying to pull repository docker.io/appsody/java-microprofile ... 
0.2: Pulling from docker.io/appsody/java-microprofile
Digest: sha256:4c95ec48f6a3fbb1637a2ac53254e295989f6bce4d790db89031abbe316d717b
Status: Image is up to date for docker.io/appsody/java-microprofile:0.2
Running command: docker run --rm -p 7777:7777 -p 9080:9080 -p 9443:9443 --name appsody-project-dev -v /root/.m2/repository:/mvn/repository -v /home/shanthir/rat/appsody-project/src:/project/user-app/src -v /home/shanthir/rat/appsody-project/pom.xml:/project/user-app/pom.xml -v appsody-controller-0.3.1:/.appsody -t --entrypoint /.appsody/appsody-controller appsody/java-microprofile:0.2 --mode=run
[Container] Running APPSODY_PREP command: ../validate.sh && mvn -B -Dmaven.repo.local=/mvn/repository install -DskipTests && /project/install-dev-deps.sh
[Container] [Warning] Failed to add directory to recursive file watching list: /project/user-applstat /project/user-app/pom.xml: permission denied
[Container] Error: Could not find Maven pom.xml
[Container] 
[Container]   * The project directory (containing an .appsody-conf.yaml file) must contain a pom.xml file.
[Container]   * On Windows and MacOS, the project directory should also be shared with Docker: 
[Container]     - Win: https://docs.docker.com/docker-for-windows/#shared-drives
[Container]     - Mac: https://docs.docker.com/docker-for-mac/#file-sharing
[Container]   
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
[Error] Error in 'appsody run': exit status 1

I have tried running appsody init without sudo and the same result.

**To Reproduce**
1. mkdir appsody-proj; cd appsody-proj
2. appsody init java-microprofile on RHEL 7
3. appsody run

[shanthir@oc7447002330 appsody-2]$ appsody run
Running development environment...
Pulling docker image appsody/java-microprofile:0.2
Running command: docker pull appsody/java-microprofile:0.2
Trying to pull repository docker.io/appsody/java-microprofile ... 
0.2: Pulling from docker.io/appsody/java-microprofile
Digest: sha256:5b3fee0a0da2f37c4585a821463997d36d57f0a1d1b7d25293cb1cd87d188659
Status: Image is up to date for docker.io/appsody/java-microprofile:0.2
Running command: docker run --rm -p 9080:9080 -p 9443:9443 -p 7777:7777 --name appsody-2-dev -v /home/shanthir/.m2/repository:/mvn/repository -v /home/shanthir/rat/appsody-2/src:/project/user-app/src -v /home/shanthir/rat/appsody-2/pom.xml:/project/user-app/pom.xml -v appsody-controller-0.3.1:/.appsody -t --entrypoint /.appsody/appsody-controller appsody/java-microprofile:0.2 --mode=run
[Container] Running APPSODY_PREP command: ../validate.sh && mvn -B -Dmaven.repo.local=/mvn/repository install -DskipTests && /project/install-dev-deps.sh
[Container] [Warning] Failed to add directory to recursive file watching list: /project/user-applstat /project/user-app/pom.xml: permission denied
[Container] Error: Could not find Maven pom.xml
[Container] 
[Container]   * The project directory (containing an .appsody-conf.yaml file) must contain a pom.xml file.
[Container]   * On Windows and MacOS, the project directory should also be shared with Docker: 
[Container]     - Win: https://docs.docker.com/docker-for-windows/#shared-drives
[Container]     - Mac: https://docs.docker.com/docker-for-mac/#file-sharing
[Container]   
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1

**Expected behavior**

**Actual behaviour**
Error
**Environment Details (please complete the following information):**
 - OS: Red Hat Enterprise Linux Workstation release 7.7 (Maipo)
 - Docker version 1.13.1, build 7f2769b/1.13.1
- Appsody version: appsody 0.5.0

**If applicable please specify:**
 - appsody 0.5.0
 - java-microprofile 0.2.20

**Screenshots**
![image (3)](https://user-images.githubusercontent.com/57804199/69623353-bbb3fe00-1068-11ea-88c3-c514068eddb3.png)

**Additional context**

**Comment by tnixa** [comment]
I believe `permission denied` is usually an issue with docker permissions. Does this problem exist with other stacks or just java-microprofile?

**Comment by shantr15** [comment]
Hi, thanks for responding. yes I face the same issue with node-express module too.

**Comment by tnixa** [comment]
@shantr15 Did you follow the SELinux instructions when you installed Appsody?
https://appsody.dev/docs/getting-started/installation
"Running Appsody with SELinux"
If not, can you try the `chcon -Rt svirt_sandbox_file_t </path/to/project>` on your project directory?
We are investigating an issue with running that command on your home directory as it may impact wireless authentication so please just try your project directory for now.
https://github.com/appsody/website/issues/401

**Comment by Kamran64** [comment]
@tnixa - I didn't realise this was a known issue so myself and @shantr15 were looking at this for some of the morning. We figured out it was an SELinux issue and we changed his configuration from there. We also found using `appsody run --docker-options "privileged"` worked for the run scenario. 

@shantr15 - Please can you give what @tnixa suggested a try for a less finicky solution.

**Comment by shantr15** [comment]
> @shantr15 Did you follow the SELinux instructions when you installed Appsody?
> https://appsody.dev/docs/getting-started/installation
> "Running Appsody with SELinux"
> If not, can you try the `chcon -Rt svirt_sandbox_file_t </path/to/project>` on your project directory?
> We are investigating an issue with running that command on your home directory as it may impact wireless authentication so please just try your project directory for now.
> [appsody/website#401](https://github.com/appsody/website/issues/401)

Thanks @tnixa - This works. I am able to run appsody run and appsody build now. I now see a small error with git though when running appsody build.

[Docker] Step 28/28 : LABEL org.opencontainers.image.title=node-proj
[Docker]  ---> Running in 4f03f757cad2
[Docker] Removing intermediate container 4f03f757cad2
[Docker]  ---> 08535782b057
[Docker] Successfully built 08535782b057
[Docker] Successfully tagged node-proj:latest
Built docker image node-proj
Running command: docker create --name node-proj-extract appsody/nodejs-express:0.2
Running command: docker cp node-proj-extract:/config/app-deploy.yaml /home/shanthir/rat/node-proj/app-deploy.yaml
Running command: docker rm node-proj-extract -f
Running git command: git version
**Running git command: git status -sb
git command failed:** 

is this something to worry about?

**Comment by shantr15** [comment]
sorry, closed the issue by mistake.

**Comment by EnriqueL8** [comment]
Hey @shantr15 , the git command error shouldn't be something to worry about. We are extracting some git information from the current directory, and that command fails if it is not a git directory. The build will still succeed, but the image built won't contain labels for the git information.

**Comment by Kamran64** [comment]
Thanks @EnriqueL8 - Closing this issue as it looks like the problem has been resolved. @shantr15 feel free to reopen if there are more issues.

**Comment by shantr15** [comment]
Thank you appsody team for helping me with this. Yes the issue is 
resolved.

Thanks,
Shanthi
