### ISSUE TITLE
Rust: appsody run/test/debug creates root owned target & Cargo.toml

### ISSUE THREAD

**Issue by slinkydeveloper** [appsody/stacks#530]
**Describe the bug**
When I run local development commands (run/test/debug) for the first time, a `Cargo.lock` and a `target` directory are created in the host project directory (which is fine) with root owner:

```
-rwxr-xr-x. 1 slinkydeveloper slinkydeveloper 1,7K 28 nov 13.00 app-deploy.yaml
-rw-r--r--. 1 root            root             143 27 nov 13.47 Cargo.lock
-rw-r--r--. 1 slinkydeveloper slinkydeveloper  538 28 nov 18.07 Cargo.toml
drwxr-xr-x. 2 slinkydeveloper slinkydeveloper 4,0K 28 nov 18.05 src
drwxr-xr-x. 3 root            root            4,0K 27 nov 13.47 target
``` 

This doesn't allow to run `cargo` commands on host like cargo check:

```
    Updating crates.io index
error: failed to write /home/slinkydeveloper/projects/rust-appsody-test/Cargo.lock

Caused by:
  failed to open: /home/slinkydeveloper/projects/rust-appsody-test/Cargo.lock

Caused by:
  Permission denied (os error 13)
```

**To Reproduce**
1. In a new directory, `appsody init experimental/rust`
2. Run an appsody local development command like `appsody run`
3. `appsody stop`
4. `cargo check` or any other cargo command reading the manifest will fail

**Expected behavior**
appsody commands creates a non-root owned `target` and `Cargo.toml` and host machine user should have read/write privileges on it 

**Actual behaviour**
`target` & `Cargo.toml` owned by user

**Environment Details (please complete the following information):**
 - OS: Fedora 29
 - Docker CE 19.03.5

**If applicable please specify:**
 - CLI version: 0.5.0
 - Stack you are using (including the version): experimental/rust 0.1.4

**Additional context**
Same problem of https://github.com/appsody/stacks/issues/518

**Comment by skoh7645** [comment]
I've failed to replicate this error on my macOS machine. After speaking with @slinkydeveloper we've realised that this is because while on linux, docker daemon runs as root. This also explains why I couldn't replicate the similar issue https://github.com/appsody/stacks/issues/518 on my local machine

**Comment by slinkydeveloper** [comment]
As a solution, we could add flag `--user $(id -u):$(id -g)` when running docker commands

**Comment by sam-github** [comment]
@skoh7645 Yes, I'm running on Linux, [too](#518):

> OS: [e.g. iOS] Ubuntu 19.10

**Comment by neeraj-laad** [comment]
closing this and tracking this as a wider issue here: Stacks should not be running as root during local development and production #622
