### ISSUE TITLE
java-microprofile should support JEE JCA connection pools

### ISSUE THREAD

**Issue by nastacio** [appsody/stacks#539]
**Is your feature request related to a problem? Please describe.**
Currently, there is no support mechanism for placing JDBC/JMS/J2C drivers into the container image, which means one cannot declare connection pools in server.xml because they need to access the non-existent driver files during runtime.

**Describe the solution you'd like**
A supported mechanism for placing these types of JAR files in the container image in a location accessible via server.xml, e.g.:

```
    <library id="db2-library">
        <fileset 
            id="db2Fileset"
            dir="${server.config.dir}/resources"
            includes="jcc*.jar"/>
    </library>
```

**Describe alternatives you've considered**
There is a workaround based on using the Maven Resource Plugin to place the driver files in a strategic location of the build tree, from where they get picked up during `appsody build`. Note that this strategic location is gleaned from inside-knowledge of the *current* stack Dockerfile, currently: `${basedir}/target/liberty/wlp/usr/servers/defaultServer/resources/`

**Additional context**

#521

**Comment by scottkurz** [comment]
Assigned @ajm01 ... I think the solution here may ultimately involve copying the JDBC driver artifact into  *target/liberty/wlp/usr/servers/defaultServer/resources/* , but we should have a pattern (or even a template) to make it more obvious how to do this, so it doesn't feel like each person needs to come up with their own hack/solution.

**Comment by scottkurz** [comment]
Related to https://github.com/appsody/stacks/issues/539

**Comment by scottkurz** [comment]
Though this issue hasn't been solved in the java-microprofile stack, relabeling to the java-openliberty stack, which is where we will prioritize a solution.

**Comment by scottkurz** [comment]
See discussion in [LMP issue 705](https://github.com/OpenLiberty/ci.maven/issues/705).

**Comment by scottkurz** [comment]
@nastacio would you say we can close this now ?

**Comment by nastacio** [comment]
Yes, I also wrote an issue for myself to update 
https://developer.ibm.com/tutorials/connecting-appsody-java-microprofile-applications-to-jdbc-data-sources/
with the new stack

thanks @scottkurz !
