### ISSUE TITLE
Default app template for java-microprofile uses a *WebSphere* Liberty maven plugin

### ISSUE THREAD

**Issue by nastacio** [appsody/stacks#544]
**Describe the bug**
WebSphere Liberty is the commercial version of Open Liberty and Appsody is an open-source project.

The problems range from optics all the way to potentially tainting the licensing terms for Appsody.

**To Reproduce**
Visual inspection of the pom.xml for the stack:
https://github.com/appsody/stacks/blob/17d8c9c5992637025efcbc6f22f3e9f8f591fb1c/incubator/java-microprofile/templates/default/pom.xml#L93

**Expected behavior**
The application template should use the Open Liberty plug in.

**Actual behaviour**
The application template should use the WebSphere Liberty plug in.

**Environment Details (please complete the following information):**
N/A

**If applicable please specify:**
 - CLI version: appsody 0.5.2
 - Stack you are using (including the version):
java-microprofile 0.2.21

**Screenshots**
N/A

**Additional context**
N/A

**Comment by scottkurz** [comment]
This is addressed by https://github.com/appsody/stacks/pull/514.

Along with that comes the idea of separating out the new function into a new openliberty stack, however.. so until we commit to that maybe it's fair to leave this issue open as-is.

**Comment by nastacio** [comment]
Now that you mention an "openliberty stack", it reminds me that I was thinking about this just a couple of days ago.

All 3 Java stacks in Appsody are capable of Eclipse MicroProfile, so "java-microprofile" is misleading.

In hindsight, it should be the "java-openliberty" stack. MicroProfile is just one out of dozens of features that can be added to an open liberty server.

**Comment by ebullient** [comment]
> There are 3 Java stacks in Appsody (java-microprofile, java-spring-boot2, quarkus) capable of supporting Eclipse MicroProfile, so "java-microprofile" is a misleading name.

java-spring-boot2-liberty, yes. java-spring-boot2, no.

**Comment by scottkurz** [comment]
The naming issues regarding the java-microprofile won't be addressed in this stack.  However, the new java-openliberty has addressed some of the points here.
