### ISSUE TITLE
Move away from single file mounts in java-microprofile stack

### ISSUE THREAD

**Issue by yeekangc** [appsody/stacks#554]
Ref https://github.com/appsody/appsody/issues/512, move java-microprofile stack away from using single file mounts due to Docker limitations.

**Comment by yeekangc** [comment]
@uberskigeek @scottkurz

**Comment by scottkurz** [comment]
Though the APPSODY_WATCH_REGEX only matches against the filename (not including dirname), seems like the variable:  APPSODY_WATCH_IGNORE_DIR   could be used to exclude **target** and thereby mount the whole project dir.

**Comment by scottkurz** [comment]
We're not going to enhance this stack in this way.  Closing.
