### ISSUE TITLE
nodejs: update nodejs stacks to use nodejs version 12

### ISSUE THREAD

**Issue by andrewhughes101** [appsody/stacks#561]
Update the nodejs, nodejs-express and nodejs-functions stacks to use nodejs version 12

- [x] nodejs stack #553 
- [x] nodejs-express stack #555 
- [ ] nodejs-functions stack #560 

Steps to update the version of nodejs across stacks:

### nodejs stack

- Update all references to Node.js v.X in the `README.md`
- In `image/Dockerfile-stack` change the following to the new version of nodejs:
  - `FROM node:X`
- In `image/project/Dockerfile` update:
  - `FROM node:X`
  - `FROM node:X-slim`
- In `templates/simple/app.js` update:
  - `console.log("Hello from Node.js X!")`
- Update the stack version in `stack.yaml` and `image/project/package.json` to a new major

### nodejs-express stack

_Do not merge the update to the express stack before merging the update to the base nodejs stack_

- Update all references to Node.js v.X in the `README.md`
- In `image/Dockerfile-stack` change the following to use the new verion of the nodejs stack:
  - `FROM appsody/nodejs:X`
- In `image/project/Dockerfile` change:
  - `FROM node:X`
  - `FROM node:X-slim`
- Update the stack version in `stack.yaml` and `image/project/package.json` to a new major

### nodejs-functions stack

_Do not merge the update to the functions stack before merging the update to the express stack_
- Update all references to Node.js v.X in the `README.md`
- In `image/Dockerfile-stack` change the following to use the new version of express stack:
  - `FROM appsody/nodejs-express:X`
- Update the stack version in `stack.yaml` and `image/project/package.json` to a new major

**Comment by sam-github** [comment]
@raymondfeng I guess nodejs-loopback will inherit these when it updates its base image to 0.3 (after it is published): https://github.com/appsody/stacks/blob/master/incubator/nodejs-loopback/image/Dockerfile-stack#L1
