### ISSUE TITLE
Fix for appsody init incubator-index/node-red none

### ISSUE THREAD

**Issue by rei-vilo** [appsody/stacks#569]
**Describe the bug**
Recommended syntax fails.

**To Reproduce**
1. Install Docker
2. Install 
3. Launch `appsody init incubator-index/node-red none`

> % appsody init incubator-index/node-red none
> [Error] Repository incubator-index is not in configured list of repositories
> 

However, `appsody list` does list `incubator  	node-red`.

> REPO        	ID                       	VERSION  	TEMPLATES        	DESCRIPTION                                              
> experimental	java-spring-boot2-liberty	0.1.11   	*default         	Spring Boot on Open Liberty & OpenJ9 using Maven         
> experimental	nodejs-functions         	0.1.6    	*simple          	Serverless runtime for Node.js functions                 
> experimental	quarkus                  	0.2.2    	*default         	Quarkus runtime for running Java applications            
> experimental	rocket                   	0.1.0    	*simple          	Rocket web framework for Rust                            
> experimental	rust                     	0.1.4    	*simple          	Runtime for Rust applications                            
> experimental	vertx                    	0.1.4    	*default         	Eclipse Vert.x runtime for running Java applications     
> *incubator  	java-microprofile        	0.2.21   	*default         	Eclipse MicroProfile on Open Liberty & OpenJ9 using Maven
> *incubator  	java-spring-boot2        	0.3.20   	*default, kotlin 	Spring Boot using OpenJ9 and Maven                       
> *incubator  	kitura                   	0.2.3    	*default         	Runtime for Kitura applications                          
> *incubator  	node-red                 	0.1.0    	*simple          	Node-RED runtime for running flows                       
> *incubator  	nodejs                   	0.3.0    	*simple          	Runtime for Node.js applications                         
> *incubator  	nodejs-express           	0.2.10   	scaffold, *simple	Express web framework for Node.js                        
> *incubator  	nodejs-loopback          	0.1.8    	*scaffold        	LoopBack 4 API Framework for Node.js                     
> *incubator  	python-flask             	0.1.6    	*simple          	Flask web Framework for Python                           
> *incubator  	starter                  	0.1.1    	*simple          	Runnable starter stack, copy to create a new stack       
> *incubator  	swift                    	0.2.3    	*simple          	Appsody runtime for Swift applications   
> 

**Expected behavior**
Successfully initialized Appsody project with the incubator/node-red stack and no template.
 

**Actual behaviour**
Error with 
> % appsody init incubator-index/node-red none
> [Error] Repository incubator-index is not in configured list of repositories

**Fix**
Launch `appsody init incubator-index/node-red none` instead

**Environment Details (please complete the following information):**
 - OS: macOS 10.15.2 (19C57)
 - Browser: Safari 13.0.4 (15608.4.9.1.3)

**If applicable please specify:**
 - CLI version: appsody 0.5.3
 - Docker version 19.03.5, build 633a0ea

**Comment by skoh7645** [comment]
@rei-vilo To initialise a new project with a stack, you would run `appsody init <repo>/<stack>`. So in your case, you would run `appsody init incubator/node-red none`, as the `node-red` stack is under the `incubator` repo, rather than `incubator-index`

**Comment by skoh7645** [comment]
Closing as this is a non-issue.
