### ISSUE TITLE
java-microprofile root owned files in .m2 directory

### ISSUE THREAD

**Issue by tnixa** [appsody/stacks#593]
**Describe the bug**
I was working with @ebullient on #558 and we believe the cause of that problem is due to root owned files in the `~/.m2/repository` directory. I appears this is due to java-microprofile not using the `ENV APPSODY_USER_RUN_AS_LOCAL=true` flag in the `image/Dockerfile-stack`. Here are some of the root owned files that were created after doing an `appsody run` of the java-microprofile stack...
```
[jenkinstest@Appsody-Test-RHEL771 java-spring-boot2]$ ls -latr ~/.m2/repository/
total 8
drwxrwxr-x  4 jenkinstest jenkinstest   39 Jan 13 11:57 ..
drwxrwxr-x  3 jenkinstest jenkinstest   17 Jan 13 11:57 ch
drwxrwxr-x  3 jenkinstest jenkinstest   19 Jan 13 11:58 junit
drwxrwxr-x  3 jenkinstest jenkinstest   24 Jan 13 11:58 commons-io
drwxrwxr-x  3 jenkinstest jenkinstest   25 Jan 13 11:58 aopalliance
drwxrwxr-x  3 jenkinstest jenkinstest   27 Jan 13 11:58 commons-codec
drwxrwxr-x  3 jenkinstest jenkinstest   25 Jan 13 11:59 classworlds
drwxrwxr-x  3 jenkinstest jenkinstest   38 Jan 13 11:59 backport-util-concurrent
drwxrwxr-x  3 jenkinstest jenkinstest   21 Jan 13 11:59 dev
drwxr-xr-x  4 jenkinstest jenkinstest   37 Jan 13 12:07 ant
drwxr-xr-x  3 jenkinstest jenkinstest   25 Jan 13 12:17 commons-cli
drwxrwxr-x  6 jenkinstest jenkinstest   64 Jan 13 12:37 net
drwxrwxr-x  9 jenkinstest jenkinstest  136 Jan 13 12:37 io
drwxrwxr-x 18 jenkinstest jenkinstest  252 Jan 13 12:39 javax
drwxrwxr-x 10 jenkinstest jenkinstest  123 Jan 13 12:39 com
drwxr-xr-x  3 root        root          19 Jan 13 12:40 log4j
drwxrwxr-x 30 jenkinstest jenkinstest 4096 Jan 13 12:40 org
drwxr-xr-x  3 root        root          26 Jan 13 12:40 commons-lang
drwxr-xr-x  4 root        root          56 Jan 13 12:40 commons-logging
drwxr-xr-x  3 root        root          26 Jan 13 12:40 commons-jexl
drwxr-xr-x  3 root        root          21 Jan 13 12:42 xmlpull
drwxr-xr-x  3 root        root          22 Jan 13 12:42 xpp3
drwxr-xr-x  3 root        root          24 Jan 13 12:42 xerces
drwxr-xr-x  3 root        root          22 Jan 13 12:42 xml-apis
drwxr-xr-x  3 root        root          33 Jan 13 12:42 commons-collections
drwxr-xr-x  3 root        root          17 Jan 13 12:42 oro
drwxr-xr-x  3 root        root          31 Jan 13 12:42 commons-validator
drwxr-xr-x  3 root        root          31 Jan 13 12:42 commons-beanutils
drwxr-xr-x  3 root        root          30 Jan 13 12:42 commons-digester
drwxr-xr-x  3 root        root          20 Jan 13 12:42 logkit
drwxr-xr-x  3 root        root          30 Jan 13 12:42 avalon-framework
drwxr-xr-x  3 root        root          27 Jan 13 12:42 commons-chain
drwxr-xr-x  3 root        root          19 Jan 13 12:42 dom4j
drwxr-xr-x  3 root        root          20 Jan 13 12:42 sslext
drwxr-xr-x  3 root        root          19 Jan 13 12:42 antlr
drwxrwxr-x 36 jenkinstest jenkinstest 4096 Jan 13 12:42 .
```

**To Reproduce**
1. remove existing directory: `rm -rf ~/.m2*`
2. `mkdir microprofile`
3. `cd microprofile`
4. `appsody init java-microprofile`
5. `appsody run`
6. `ls -latr ~/.m2/repository` to see root owned files

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] RHEL 7.7

**If applicable please specify:**
 - CLI version: 0.5.4
 - Stack you are using (including the version): java-microprofile

**Comment by sam-github** [comment]
possibly related to:
- https://github.com/appsody/stacks/issues/518
- https://github.com/appsody/stacks/issues/550

**Comment by scottkurz** [comment]
In spite of the fact that we're now prioritizing java-openliberty as a strategic alternative to the java-microprofile stack, it seems like there would still be value in fixing this, for anyone following older/existing documentation.    

Assuming there's no back-compatibility concern (that someone would want the files owned by 'root') I think we could fix this.    @neeraj-laad  what do you think?

**Comment by neeraj-laad** [comment]
@groeges I guess your recent PR should fix this issue.

**Comment by scottkurz** [comment]
I'm not sure about the userid/ownership changes in https://github.com/appsody/stacks/pull/655.   I think we should consider living with these issues until the end of its life.

**Comment by neeraj-laad** [comment]
Trackign tehse as wider issue here: https://app.zenhub.com/workspaces/appsody-zenhub-5d15215ee0945f63bfe31734/issues/appsody/stacks/622

Closing individual stack issues.
