### ISSUE TITLE
Upgrade from JUnit 4 to JUnit 5 in java-openliberty stack

### ISSUE THREAD

**Issue by nastacio** [appsody/stacks#595]
**Is your feature request related to a problem? Please describe.**
JUnit 5 has significant functional improvements over JUnit 4 and also has support across all major IDEs. 

**Describe the solution you'd like**
The current java-openliberty stack templates use JUnit 4. I would like for them to use JUnit 5 starter code.

**Describe alternatives you've considered**
There are no alternatives, this is more a matter of currency than design change.

**Additional context**
None.

**Comment by scottkurz** [comment]
+1... another thought is that the [Microshed test project](https://microshed.org/microshed-testing/)  uses JUnit 5.  I'd  like to explore integration with MST so better not to start with JUnit 4.
