### ISSUE TITLE
java-openliberty:  Pick up LMP V3.2 and delegate to liberty-maven-plugin to watch pom.xml changes

### ISSUE THREAD

**Issue by scottkurz** [appsody/stacks#608]
As commented [here](https://github.com/appsody/stacks/blob/deb09f9d8a404b6105a4ee4e56ebce6d9c5e6614/incubator/java-openliberty/image/Dockerfile-stack#L29-L30) we are using the appsody watcher to watch pom.xml as a workaround to v3.1 liberty-maven-plugin limitations.

Once https://github.com/OpenLiberty/ci.maven/pull/676 is available in a release, we should move our appsody stack to that version of the plugin, and remove this special case exception from our appsody watcher.

**Comment by uberskigeek** [comment]
Looks like this will be available with LMP Version 3.2

**Comment by scottkurz** [comment]
https://github.com/OpenLiberty/open-liberty/issues/10674  is somewhat important to appsody java-openliberty.   I suggest we either wait until 20.0.0.2 is available and do together, or at least open a follow-up issue if we do the LMP upgrade alone.
