### ISSUE TITLE
Setup and document Travis setup for one stack

### ISSUE THREAD

**Issue by EnriqueL8** [appsody/stacks#609]
**Is your feature request related to a problem? Please describe.**
Create a document/tutorial on setting up a travis CI for validating, packaging and publishing a stack. This would be focused at a github repo with one stack only.

**Describe the solution you'd like**
Modify the stacks repo CI to handle a single stack, and only use the appsody cli commands such as `package`, and `validate`. Write a tutorial/document on how to get this setup, explaining the process of adding Travis CI to a github repo and any permissions for docker.

**Comment by neeraj-laad** [comment]
We should also think and document how #312 will fit in this kind of environment.

**Comment by groeges** [comment]
@neeraj-laad Is #312 the issue you were intending to reference above. This is a PR for pipelines which you commented as being invalid for Appsody.

**Comment by neeraj-laad** [comment]
Closing this for now as we have documentation on building and publishing a stack already and there are docs for repo-tools too.
