### ISSUE TITLE
Kitura stack fails to run if `appsody init` fails

### ISSUE THREAD

**Issue by makandre** [appsody/stacks#610]
## Summary

First, for some context, this is what occurs when an appsody project is created in Codewind:

1. Codewind downloads and untars the project template
2. Codewind calls `appsody init` in the project directory

If step 2 fails, we would get following warnings:

```
Setting up the development environment
Pulling docker image docker.io/appsody/kitura:0.2
Running command: docker pull docker.io/appsody/kitura:0.2
[Warning] Docker image pull failed: exec: "docker": executable file not found in $PATH
[Warning] Could not run docker image ls -q for the image: appsody/kitura:0.2 error: exec: "docker": executable file not found in $PATH Check to make sure docker is available.
[Warning] The stack init script failed: Could not find the image either in docker hub or locally: docker.io/appsody/kitura:0.2
[Warning] Your local IDE may not build properly, but the Appsody container should still work.
[Warning] To try again, resolve the issue then run `appsody init` with no arguments.
Successfully initialized Appsody project with the  stack and the default template.
```

Specifically, the message states that **Your local IDE may not build properly, but the Appsody container should still work.**

With other stacks, this is true and we can run with `appsody run` and the application works fine.

But this is not true for the Kitura stack.  It appears for Kitura stack, the `init` step creates an `.appsody` folder in the project which is required to run the application.

## Question

Is it a bug that the Kitura fails to run in this case, or is `appsody init` required to succeed, contrary to what the warnings states?

**Comment by makandre** [comment]
This is the error given during run:

```
[Container] Running APPSODY_PREP command: if [ -n "$(diff -rq /project/deps /project/user-app/.appsody)" ]; then rm -rf /project/user-app/.appsody && cp -R -p /project/deps /project/user-app/.appsody; fi
[Container] diff: /project/user-app/.appsody: No such file or directory
[Container] Running command:  swift run
[Container] error: Error Domain=NSCocoaErrorDomain Code=260 "The file doesn’t exist."
[Container] Wait received error on APPSODY_RUN/DEBUG/TEST exit status 1
```

**Comment by makandre** [comment]
@neeraj-laad is there an update?

**Comment by skoh7645** [comment]
@makandre This is a bug, the init script should not have any affect on the container.
