### ISSUE TITLE
python-flask on linux: stack validate run and test fail cannot create requirements.txt: Permission denied

### ISSUE THREAD

**Issue by tnixa** [appsody/stacks#621]
**Describe the bug**
Running BATS integration test with the latest stack and cli code via Jenkins to Ubuntu and RHEL VMs and both are failing on `stack validate` during the `run` and `test` steps with the error below...

```[Container] Running APPSODY_PREP command: cd /project/userapp;pipenv lock -r > requirements.txt;python -m pip install -r requirements.txt -t /project/deps
[Container] /bin/sh: 1: cannot create requirements.txt: Permission denied
[Container] ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
[Container] [Error] FATAL error APPSODY_PREP command received an error.  The controller is exiting: exit status 1
[Debug] CLI exit error is:  exit status 1
[Error] Error in 'appsody test': exit status 1
```
Full log is here:
[stack-validate-python-flask.log](https://github.com/appsody/stacks/files/4105267/stack-validate-python-flask.log)

**To Reproduce**
1. Go to `stacks/incubator/python-flask`
2. `appsody stack validate`

**Environment Details (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.0.4 and RHEL 7.7

**If applicable please specify:**
 - CLI version: latest dev
 - Stack you are using (including the version): python-flask

**Comment by skoh7645** [comment]
I couldn't replicate this on my linux VM

**Comment by Kamran64** [comment]
I can't replicate this locally on my Ubuntu vm (also 18.04) but the travis build for https://github.com/appsody/stacks/pull/660 is failing for the same reason. @henrynash have you seen this before?

**Comment by henrynash** [comment]
I had not seen this before....but looks like you have a fix proposed....

**Comment by Kamran64** [comment]
@henrynash I added the `APPSODY_USER_RUN_AS_LOCAL` env var in https://github.com/appsody/stacks/pull/660 which seems to have fixed the problem. I think the userapp directory was created with a different owner to the user inside the container hence the permission denied.

**Comment by EnriqueL8** [comment]
@Kamran64 Can we close this then?
