### ISSUE TITLE
Java-microprofile inconsistent Liberty version when doing appsody build vs run

### ISSUE THREAD

**Issue by navidsh** [appsody/stacks#644]
**Describe the bug**
I got two different versions of Open Liberty when running Micro Profile stack (`appsody run`) locally VS building and running (`appsody build` followed by `docker run`). 

`appsody run`: `Open Liberty 20.0.0.1/wlp-1.0.36.cl200120200108-0300`
`appsody build` followed by `docker run`: `Open Liberty 19.0.0.8/wlp-1.0.31.cl190820190813-1136`

**To Reproduce**
1. `appsody init java-microprofile`
2. `appsody build`
3. `docker run dev.local/microprofile`
4. `appsody run`

**Expected behavior**
Expected to see the same version of Open Liberty to run my application.

**Actual behaviour**
```
⇒  docker run dev.local/microprofile

Launching defaultServer (Open Liberty 20.0.0.1/wlp-1.0.36.cl200120200108-0300) on Eclipse OpenJ9 VM, version 1.8.0_242-b08 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
..
```

```
⇒  appsody run
...
[Container] [INFO] Launching defaultServer (Open Liberty 19.0.0.8/wlp-1.0.31.cl190820190813-1136) on Eclipse OpenJ9 VM, version 1.8.0_222-b10 (en_US)
[Container] [INFO] [AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[Container] [INFO] [AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /project/user-app/target/liberty/wlp/usr/servers/defaultServer/configDropins/defaults/server.xml
[Container] [INFO] [AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
...
```

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version: `0.5.8`
 - Stack you are using (including the version): `java-microprofile 0.2.22`

**Screenshots**
N/A

**Additional context**
N/A

**Comment by scottkurz** [comment]
The java-microprofile stack hasn't been providing a consistent Open Liberty fixpack until now.  This has been done in the kabanero collections fork.     I'm not saying we couldn't but I'm just wondering about the plan.   Is there no fork now?

**Comment by kilnerm** [comment]
@scottkurz The Kabanero collections fork is being put into maintenance mode and will only receive security related updates moving forwards until it reaches end of life. At this time the fork is no longer a target stack for Kabanero users.
