### ISSUE TITLE
Nodejs stacks fail to run without Internet access

### ISSUE THREAD

**Issue by makandre** [appsody/stacks#646]
**Is your feature request related to a problem? Please describe.**

I'm trying to use Appsody in air-gap scenarios:

1. Create appsody projects while still connected to the Internet
2. Cut Internet access (imagine if I was boarding a plane)
3. If my appsody projects were running prior to the connection loss, I can still work on the projects. Changes I make are picked up by the controller and the application is restarted
4. But if I need to run `appsody run` while disconnected, it fails at the `npm audit` step:

```
[Container] [0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mnetwork[0m request to https://registry.npmjs.org/-/npm/v1/security/audits failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org
```

Stacks tested which exhibit this problem:
- `nodejs-express`
- `node-red`

Stacks tested not affected by this problem:
- `nodejs-loopback`

**Describe the solution you'd like**

Can `npm audit` failures be warnings and not fail `appsody run`?

**Describe alternatives you've considered**

**Additional context**

**Comment by sam-github** [comment]
Warnings would be ignored, and security warnings should not be.

But I'm not insensitive to the difficulties of getting stuff done on an airplane.

Other than forking the stack, which appsody has good support for, I'm not sure if  there are other mechanisms for customizing the stack behaviour.

at-appsody developers, any opinions here? What do other stacks do, for audit, or just generally?

Btw, what about `npm install`, doesn't that cause problems? I've had to hunt my drives on a an airplane before, looking for npm deps, I'm surprised it doesn't break as well.

**Comment by makandre** [comment]
Re `npm install`: since I created the project and ran it at least once while connected, I think the dependencies were dowloaded to the `<projectname>-dep` docker volume and did not need to be downloaded again while offline.

**Comment by makandre** [comment]
I tested with new stacks and this scenario now works, thanks.
