### ISSUE TITLE
Support deprecation of a stack

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#653]
We need a clear mechanism to flag that a stack is deprecated.

- How does stack maintainer or release team flag that a stack is deprecated?
- How does to user know that the stack is now deprecated?
- How do users continue to use it if they wish to?
- How long do we wait before deleting?

**Comment by neeraj-laad** [comment]
@scottkurz @groeges Would like to get your thoughts on this.

**Comment by neeraj-laad** [comment]
During Deprecation:
- Keep behaviour as is
- Add a flag in stack.yaml
```
deprecated: <deprecation message string>
```
- Update CLI to read the index and add a warning message for deprecation using the string.
- Indicate deprecation on website

Deprecation duration: at least 3 months but can be more if stack creator wants

Beyond deprecation:
- Delete the stack from the repo (users can not init, run etc)
- Leave previous releases as is (users can use that if really needed)
- Leave previous images as is

**Comment by groeges** [comment]
It might also be nice to be able to see whether a stack is deprecated when doing an `appsody list` command. In this way the user can see this before trying to do an `appsody init` and then finding out the stack is deprecated.

**Comment by scottkurz** [comment]
I can't think of anything else on top of all the details you laid out @neeraj-laad , plus the `appsody list` is a good idea too.
