### ISSUE TITLE
Error while validating "kotlin" template of java-spring-boot2 stack on PPC64LE

### ISSUE THREAD

**Issue by vrushaliinamdar** [appsody/stacks#662]
I am getting following error while validating the java-spring-boot2 appsody stack:

```
[Docker] [ERROR] /project/user-app/src/main/kotlin/application/Hello.kt: (9, 17) Type mismatch: inferred type is kotlin.String but java.lang.String was expected
[Docker] [ERROR] /project/user-app/src/main/kotlin/application/LivenessEndpoint.kt: (22, 2) Cannot access class 'java.lang.String'. Check your module classpath for missing or conflicting dependencies
[Docker] [ERROR] /project/user-app/src/main/kotlin/application/LivenessEndpoint.kt: (22, 16) Type mismatch: inferred type is kotlin.String but java.lang.String was expected
[Docker] [ERROR] /project/user-app/src/main/kotlin/application/LivenessEndpoint.kt: (23, 2) Cannot access class 'java.lang.String'. Check your module classpath for missing or conflicting dependencies
..
[Docker] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Docker] java.io.FileNotFoundException: ../*.jar (No such file or directory)
[Docker]        at java.io.FileInputStream.open0(Native Method)
[Docker]        at java.io.FileInputStream.open(FileInputStream.java:212)
[Docker]        at java.io.FileInputStream.<init>(FileInputStream.java:152)
[Docker]        at java.io.FileInputStream.<init>(FileInputStream.java:104)
[Docker]        at sun.tools.jar.Main.run(Main.java:319)
[Docker]        at sun.tools.jar.Main.main(Main.java:1300)
[Docker] The command '/bin/sh -c /project/util/check_version build  && /project/java-spring-boot2-build.sh package  && /project/java-spring-boot2-build.sh createStartScript' returned a non-zero code: 1
```
@@@@@@@@@@@@@@@ Validate Summary Start @@@@@@@@@@@@@@@@
PASSED: Lint for stack:java-spring-boot2
PASSED: Package for stack:java-spring-boot2
PASSED: Init for stack:java-spring-boot2 template:default
PASSED: Run for stack:java-spring-boot2 template:default
PASSED: Test for stack:java-spring-boot2 template:default
PASSED: Build for stack:java-spring-boot2 template:default
PASSED: Init for stack:java-spring-boot2 template:kotlin
PASSED: Run for stack:java-spring-boot2 template:kotlin
**FAILED: Test for stack:java-spring-boot2 template:kotlin
FAILED: Build for stack:java-spring-boot2 template:kotlin**
Total PASSED: 8
Total FAILED: 2
@@@@@@@@@@@@@@@ Validate Summary End @@@@@@@@@@@@@@@@

**Environment Details :**
OS: Linux
ARCH: ppc64le
CLI version: appsody 0.5.8
Stack you are using (including the version): java-spring-boot2 0.3.24

It seems that 'java.lang.String' is not getting resolved.  Any pointers in this regard would be of great help.

**Comment by vrushaliinamdar** [comment]
Attaching the full log 
[java-spring-boot2_3.0.24_validation.log](https://github.com/appsody/stacks/files/4197356/java-spring-boot2_3.0.24_validation.log)

**Comment by BarDweller** [comment]
Oddly this seemed to come down to a jvm/jdk issue on ppc64le, the same project builds fine on x64, and on ppc64le using a different jvm.. have submitted a pr to migrate the stack to the eclipse openj9 maven base image, this should resolve it.

**Comment by vrushaliinamdar** [comment]
@BarDweller 

It worked after changing the base image.

Thanks!
