### ISSUE TITLE
quarkus: stack is experimental

### ISSUE THREAD

**Issue by ianpartridge** [appsody/stacks#663]
## Summary

The Quarkus stack is currently in "experimental".

We are currently considering building part of a microservices scenario using Quarkus and Appsody.

I would like to know the current roadmap for the Quarkus stack and when it might be moved to "incubator".

Thanks.

**Comment by skoh7645** [comment]
Look at the requirements for an incubator stack (https://appsody.dev/docs/stacks/stacks-overview#incubator), the `quarkus` stack does meet the technical requirements necessary. It would have to be the stack maintainer, @paulrobinson, who decide if he thinks the stack is ready to be promoted to "incubator".

**Comment by ianpartridge** [comment]
Thanks @skoh7645.

@paulrobinson can you share any info? Thanks.

**Comment by paulrobinson** [comment]
Hi. Sorry for the delay on this. I'm hoping to take a look at this Monday or Tuesday (failing that it will be a further week later, due to my vacation).

**Comment by paulrobinson** [comment]
Looking at the criteria, I think that the Quarkus stack can progress to 'incubator' status. 

The Quarkus version does need upgrading, but I can raise a PR for that now.

**Comment by ianpartridge** [comment]
Awesome, thanks @paulrobinson!

**Comment by paulrobinson** [comment]
FYI: Here's the PR to upgrade Quarkus: https://github.com/appsody/stacks/pull/674

**Comment by neeraj-laad** [comment]
This stack has been promoted to `incubator` level. Closing issue.
