### ISSUE TITLE
spring: add Kafka-enabled template/stack

### ISSUE THREAD

**Issue by ianpartridge** [appsody/stacks#695]
**Is your feature request related to a problem? Please describe.**

Currently, developers who want to build Spring applications using Appsody which talk to Kafka have to roll everything themselves.

**Describe the solution you'd like**

An easy way for developers to build event-driven Kafka app on Spring, with Appsody.

**Additional context**

This could be done through [spring-kafka](https://spring.io/projects/spring-kafka) or [spring-cloud-stream](https://spring.io/projects/spring-cloud-stream).

**Comment by richard-trotter** [comment]
Here is a sample app that "illustrates the use of an IBM Event Streams Spring Boot "starter" to assist Event Streams service integration"

Using Appsody in Spring Microservice Development for Kubernetes
https://github.com/richard-trotter/appsody4springsvc2k8s

As I recall, the work required on the part of the developer is:
1. add POM dependencies
2. add configuration properties to application.yaml
3. create a K8s Secret with Event Streams credentials
4. implement the application code, integrating via org.springframework.kafka API

**Comment by ianpartridge** [comment]
Nice, those are certainly things we can help developers with via a bespoke stack/template.

NB. service binding to Strimzi is planned to be via https://github.com/redhat-developer/service-binding-operator (@arthurdm is on point there) :)

**Comment by ianpartridge** [comment]
This was delivered via https://github.com/appsody/stacks/pull/742 :)
