### ISSUE TITLE
java-openliberty:  Add stack.yaml variables (go templates): parentpomgroup, parentpomid

### ISSUE THREAD

**Issue by scottkurz** [appsody/stacks#699]
Pretty self-explanatory, see the java-spring-boot2 stack for examples.

**Comment by scottkurz** [comment]
Another thought:   

Perhaps we could add some doc, e.g. "commonly seen issues" to describe the problem when you develop your own fix (x.y.z) version of an existing stack, which "pollutes" your local .m2 repo.

The use case I have in mind is when you later, from a different project, try to use the actually-released latest version of the stack, and then the [0.2,0.3) syntax mistakenly matches your local entries in **maven-metadata-local.xml**, **resolver-status.properties**, such that you have to delete those files.   E.g. if the latest release is actually v 0.2.24 but just for a quick test I packaged a 0.2.25 in my local .m2 .. but forgot about it, then later it can cause issues.  

(I realize that description above could be better... it's a reminder to at least think about this some more, though not sure anyone would know what I meant by that yet.) And the connection to this issue is that if you always customize your `parentpomgroup` well, you'd never hit this condition.

**Comment by awisniew90** [comment]
@scottkurz - regarding the scenario above, this doesn't see like something Jane would come across, but moreso Champ while developing changes to his custom stack. Thinking we may want to expand our readme to include a "stack development" section where we can note the template variables and the enforcer plugin rules as tools when building a stack.
