### ISSUE TITLE
Kerystore.xml perms not set correctly

### ISSUE THREAD

**Issue by uberskigeek** [appsody/stacks#705]
**Describe the bug**
https://github.ibm.com/IBMCloudPak4Apps/icpa-system-test/issues/355

**To Reproduce**

**Expected behavior**
Server should start and the keystore.xml should have permissions that allow access to it. 
**Actual behaviour**
What is the actual behaviour.
permissions on keystone.xml are 000
**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using (including the version):

**Screenshots**

**Additional context**

**Comment by Kamran64** [comment]
Fixed in #706
