### ISSUE TITLE
Swift 5.2 Support

### ISSUE THREAD

**Issue by j-rabie** [appsody/stacks#752]
Hi,

Vapor 4 is out and I'm so excited to use appsody with it for the coming projects. The only issue right now is that appsody will not work with Vapor 4 projects because the new release requires Swift 5.2.

Any plan in the near future to update swift stack to the version 5.2. 
If you can provide an estimated release date, it would be SUPER!

**Comment by neeraj-laad** [comment]
@j-rabie Thanks for opening this issue. We would be delighted to see more use of Appsody. Typically, we request stack maintainers to provide updates specific to application stacks, but also welcome PRs from anyone.

@ianpartridge @djones6 Please see above request.
