### ISSUE TITLE
java-openliberty: Notify developer of quick-start-security.xml removal

### ISSUE THREAD

**Issue by uberskigeek** [appsody/stacks#756]
**Describe the bug**
The developer is not warned of the removal of the quick-start-security.xml when doing an appsody deploy. 
**Expected behavior**
A clear WARNING message of saying quick-start-security.xml is not safe for production and therefore it is removed during deploy. Also please add a comment in quick-start-security.xml to warn people. Also document this in README.md.

**Actual behaviour**
A message was printed during appsody deploy but it got bury into a long output.

**Comment by scottkurz** [comment]
Fixed by #759
