### ISSUE TITLE
Rust Tide Stack

### ISSUE THREAD

**Issue by No9** [appsody/stacks#769]
## Summary
Rust tide is modular web framework built on the new async/await features in Rust
https://github.com/http-rs/tide 

It has a composable architecture very similar to the node.js middleware approach which I believe makes it a good fit for appsody 

I have put together a baseline stack here https://github.com/No9/rust-tide and wondered if you would be interested in a PR to this repo?

**Comment by neeraj-laad** [comment]
Contributions are always welcome! Look fwd to a PR for this stack.

**Comment by neeraj-laad** [comment]
Hi.. I was wondering if you still intend to submit a PR in the appsody stack repo?

**Comment by No9** [comment]
Hi @neeraj-laad 
I was looking at health checks but I think we can move forward with what is there.
One question though.
The down stream project Tide is moving quite fast - My stack uses tide:0.7 but it has already moved to tide:0.8.1 I can updated it no problem but I expect there will be similar churn for a while. 
Does it make sense to PR this now or wait until tide has settled down more?
Don't want to overload the whoever handles the PRs with unnecessary noise.
