### ISSUE TITLE
CI scripts seem to build the wrong stack when changes to a template are pushed

### ISSUE THREAD

**Issue by chilanti** [appsody/stacks#782]
**Describe the bug**
We noticed that when we push changes to a template within a stack, the modified stack isn't rebuilt. Another stack - presumably the one that comes "next" - gets built instead.

**To Reproduce**
1. Fork the repo and clone it.
2. Make a change to a template (for example, a trivial code change in the starter app)
3. Push the changes
4. Watch Travis skip your stack and build another one instead.
Example: 
```
- SKIPPING stack image: incubator/blockchain-client-openliberty
~/build/IBM-Blockchain/appsody-stacks
/home/travis/build/IBM-Blockchain/appsody-stacks/incubator/java-microprofile/stack.yaml
~/build/IBM-Blockchain/appsody-stacks/incubator/java-microprofile ~/build/IBM-Blockchain/appsody-stacks
- LINTING stack: incubator/java-microprofile
```
In this case - we changed the template application in `blockchain-client-openliberty`, but `java-microprofile` gets built instead.

**Expected behavior**
Build the right stack.

**Actual behaviour**
Built the wrong stack.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using (including the version):

**Screenshots**

**Additional context**

**Comment by neeraj-laad** [comment]
@chilanti are you changing anything in `stack.yaml` when you add the template?

We use change in `stack.yaml` as an indicator that the stack needs to be built. and avoid builds for other changes. If not stack is updated then we default to a smaller set of stacks. 

Jut wanted to check if we are hitting this path.

**Comment by groeges** [comment]
@neeraj-laad @chilanti Neeraj, that is correct.  If the commit that is pushed doesn't have a change to stack.yaml then the scripts don't add the stack to the list of stacks to build and default to a base set of stacks to build/test.

**Comment by chilanti** [comment]
Yep - no changes for the most part to stack.yaml. So - do we need to push a "dummy" change to that every time?

**Comment by chilanti** [comment]
@groeges and @neeraj-laad - is the recommended practice that the `stack.yaml` should change for the build process to pick up the stack? It seems to be suggested even in the guidelines to submit a PR. If that's the case - please confirm - and we can close the issue.

**Comment by neeraj-laad** [comment]
@chilanti This is the current process. CI will only build and release a new stack if there is a change to `stack.yaml`. 

This helps in avoiding releases for changes that do not warrant a new release (README etc.), and helps with reminding stack creators to think if the change is compatible/non-compatible with every PR.

Closing this issue for now. Please re-open if you see this is a concern or not working as designed.
