### ISSUE TITLE
java-spring-boot2 produces large call stack, if legal java code change made

### ISSUE THREAD

**Issue by kewegner** [appsody/stacks#84]
**Describe the bug**
Small valid java change produces java call stack, server app continues to run correctly.

**To Reproduce**
1. Create a new project directory to 
2. run the command 'appsody init java-spring-boot2'
3. run the command 'appsody run'
4. add '//' to the code below (see the line after the main function for an example)
<project/src/main/java/application/Main.java>

        public static void main(String[] args) {
                SpringApplication.run(Main.class, args);
        }
//
        // Simple custom liveness check
        @Endpoint(id = "liveness")
        @Component
        public class Liveness {
                @ReadOperation
                public String testLiveness() {
                        return "{\"status\":\"UP1\"}";
                }
        }
}

**Expected behavior**
We made a tiny valid java file change and we just expect no error.

**Actual behavior**
What is the actual behavior.

[Container] 2019-07-15 13:36:58.868  WARN 204 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [application.Main]; nested exception is java.io.FileNotFoundException: class path resource [application/Main.class] cannot be opened because it does not exist
[Container] 2019-07-15 13:36:58.876 ERROR 204 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed
[Container] 

It is possible to successfully call the liveness URL: http://localhost:8080/actuator/liveness

Large call stack is produced, see attached file

**Environment Details (please complete the following information):**
 - OS: macOS
 - Browser Firefox/Crhome
 - Version 2.0.3

**If applicable please specify:**
 - CLI version: 2.4
 - Stack you are using: appsody/java-spring-boot2:0.3

**Additional context**
This error happens continuously.  It doesn't appear to go away.
[springerror.txt](https://github.com/appsody/stacks/files/3393597/springerror.txt)

**Comment by ebullient** [comment]
This is a timing window that is difficult to avoid when changing the Main class of a Spring Boot application (which is, in practice, _extremely uncommon_).

This isn't something appsody has control over.

**Comment by ebullient** [comment]
Made less likely by #210, which made the Main class a less likely target for incremental update
