### ISSUE TITLE
nodejs-express kafka consumer returns empty object

### ISSUE THREAD

**Issue by josiemundi** [appsody/stacks#848]
**Describe the bug**
The nodejs-express kafka starter app returns an empty object when trying to consume a message from the topic. 

**To Reproduce**
- Appsody run as per readme instructions
- Produce a message to the my-topic queue
- Consume a message 

**Expected behavior**
When I produce a message to the my-topic topic I am expecting to see that message when I consume from that topic.  

**Actual behaviour**
Consuming returns an empty object

**Environment Details (please complete the following information):**
 - Docker desktop for mac

**If applicable please specify:**
 - CLI version:
 - Stack you are using (including the version): nodejs-express kafka

**Screenshots**
<img width="868" alt="emptyobject" src="https://user-images.githubusercontent.com/8045393/88188394-516b5180-cc27-11ea-9c6c-9a490852ce3d.png">

**Additional context**

**Comment by neeraj-laad** [comment]
@ianpartridge @djones6 Would you be able to take a look at this one?

**Comment by josiemundi** [comment]
@neeraj-laad I spoke with @ianpartridge and confirm we will try to have a look. Just raising so it can be tracked.

**Comment by josiemundi** [comment]
@neeraj-laad I have solved this. It is because it is expecting a json object. I will add some extra information to the readme so that it is clear.

**Comment by neeraj-laad** [comment]
@josiemundi Thanks! Let's use this issue to track that README change.
