### ISSUE TITLE
Application health check java error still returns 200 with output.

### ISSUE THREAD

**Issue by kewegner** [appsody/stacks#85]
**Describe the bug**
The correct output of the java-microprofile sample for health
http://localhost:9080/health is:

checks |  
-- | --
0 |  
data | {}
name | "StarterService"
state | "UP"
outcome | "UP"

If You introduce a bug in the code.

There is still output:

  |  
-- | --
checks | []
outcome | "UP"

And it is not clear there is an error

**To Reproduce**
1. create a new project directory
2. Make sure maven is in your PATH
2. run 'appsody init java-microprofile'
3. Edit <projectdir>/src/main/java/dev/appsody/starter/health/StarterHealth.java
Add 'bbb' as follows:

    private boolean isHealthy() {
        // perform health checks here

        return true;
    }
bbb

3. run 'appsody run'
4. run http://localhost:9080/health

**Expected behavior**
Some kind of error message

**Actual behaviour**

Partial output (above) with no indication of error)

**Environment Details (please complete the following information):**
 - OS: macOS
 - Browser: firefox

**If applicable please specify:**
 - CLI version:2.4
 - Stack you are using:appsody/java-microprofile:0.2.2

**Comment by neeraj-laad** [comment]
@Emily-Jiang Perhaps you can help with this?

**Comment by Emily-Jiang** [comment]
I would like to redo the Health template based on MicroProfile Health 2.0. @neeraj-laad is Liberty 19.0.0.7 in the stack?

**Comment by Emily-Jiang** [comment]
I have now updated the stack to use MP Health 3.0. I took a detailed look at this issue. If you save it, the app will not be able to compile. I tried it out using your steps and I got a compilation error when I issue `appsody run`. Is it possible you have not saved your update?

**Comment by scottkurz** [comment]
Just tried as well with a recent `java-microprofile` stack app and I don't see this problem.  Closing.
