### ISSUE TITLE
identify the stacks that need to be built

### ISSUE THREAD

**Issue by mhamwala** [appsody/stacks#96]
**Is your feature request related to a problem? Please describe.**
Currently, we are releasing each stack manually. Prone to human error and a lot of churn.

**Describe the solution you'd like**
Setting up a travis build to detect which stacks have changed. If we are not in a PR then we should build all stacks.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by neeraj-laad** [comment]
This is in place now.
