### ISSUE TITLE
generate new template tars from travis build

### ISSUE THREAD

**Issue by mhamwala** [appsody/stacks#97]
**Is your feature request related to a problem? Please describe.**
Currently, we are releasing each stack manually. Prone to human error and a lot of churn.

**Describe the solution you'd like**
Create a new release of the stacks using https://github.com/appsody/stacks/issues/96.
This release should generate new tars from the templates in this format `<id-v<version>`.

**Describe alternatives you've considered**
This process might change once we decide on where we are going to store the tars.

**Additional context**
n/a

**Comment by neeraj-laad** [comment]
this is complete now
